-- ----------------------------
-- Records of systemadmin
-- ----------------------------
INSERT INTO `systemadmin` VALUES (1, 'admin', '2018-07-27', 'Male', 'Unknown haha', 'edu@jkt.co.id', '', '', '2018-07-27', 'default.png', 'administrator', '50644845050433f077a3c8c620fc0f78797d032e2e1e3c9b7ec9a5431fa1dce6aa8f565df9c44d4001f2d697918cabf40bbe8ea1e75d3d0183068fa1d953f5aa', 1, '2018-07-27 03:52:21', '2018-07-27 03:52:21', 0, 'administrator', 'Admin', 1, '', '');

-- ----------------------------
-- Records of setting
-- ----------------------------
INSERT INTO `setting` VALUES ('address', '');
INSERT INTO `setting` VALUES ('attendance', '');
INSERT INTO `setting` VALUES ('attendance_notification', 'none');
INSERT INTO `setting` VALUES ('attendance_notification_template', '0');
INSERT INTO `setting` VALUES ('attendance_smsgateway', '0');
INSERT INTO `setting` VALUES ('automation', '5');
INSERT INTO `setting` VALUES ('auto_invoice_generate', '0');
INSERT INTO `setting` VALUES ('backend_theme', 'default');
INSERT INTO `setting` VALUES ('captcha_status', '1');
INSERT INTO `setting` VALUES ('currency_code', 'IDR');
INSERT INTO `setting` VALUES ('currency_symbol', 'Rp');
INSERT INTO `setting` VALUES ('email', '');
INSERT INTO `setting` VALUES ('footer', 'Powered by BRI');
INSERT INTO `setting` VALUES ('frontendorbackend', 'YES');
INSERT INTO `setting` VALUES ('frontend_theme', 'default');
INSERT INTO `setting` VALUES ('language', 'english');
INSERT INTO `setting` VALUES ('language_status', '0');
INSERT INTO `setting` VALUES ('note', '1');
INSERT INTO `setting` VALUES ('phone', '');
INSERT INTO `setting` VALUES ('photo', 'site.png');
INSERT INTO `setting` VALUES ('schoolID', @schoolID);
INSERT INTO `setting` VALUES ('school_type', 'classbase');
INSERT INTO `setting` VALUES ('school_year', '1');
INSERT INTO `setting` VALUES ('sname', @sname);
INSERT INTO `setting` VALUES ('student_ID_format', '1');
INSERT INTO `setting` VALUES ('updateversion', '4.0');
INSERT INTO `setting` VALUES ('weekends', '');
INSERT INTO `setting` VALUES ('mark_1', '1');


-- ----------------------------
-- Records of permission_relationships
-- ----------------------------
INSERT INTO `permission_relationships` VALUES (501, 1);
INSERT INTO `permission_relationships` VALUES (502, 1);
INSERT INTO `permission_relationships` VALUES (503, 1);
INSERT INTO `permission_relationships` VALUES (504, 1);
INSERT INTO `permission_relationships` VALUES (505, 1);
INSERT INTO `permission_relationships` VALUES (506, 1);
INSERT INTO `permission_relationships` VALUES (507, 1);
INSERT INTO `permission_relationships` VALUES (508, 1);
INSERT INTO `permission_relationships` VALUES (509, 1);
INSERT INTO `permission_relationships` VALUES (510, 1);
INSERT INTO `permission_relationships` VALUES (511, 1);
INSERT INTO `permission_relationships` VALUES (512, 1);
INSERT INTO `permission_relationships` VALUES (513, 1);
INSERT INTO `permission_relationships` VALUES (514, 1);
INSERT INTO `permission_relationships` VALUES (515, 1);
INSERT INTO `permission_relationships` VALUES (516, 1);
INSERT INTO `permission_relationships` VALUES (517, 1);
INSERT INTO `permission_relationships` VALUES (518, 1);
INSERT INTO `permission_relationships` VALUES (519, 1);
INSERT INTO `permission_relationships` VALUES (520, 1);
INSERT INTO `permission_relationships` VALUES (521, 1);
INSERT INTO `permission_relationships` VALUES (522, 1);
INSERT INTO `permission_relationships` VALUES (523, 1);
INSERT INTO `permission_relationships` VALUES (524, 1);
INSERT INTO `permission_relationships` VALUES (525, 1);
INSERT INTO `permission_relationships` VALUES (526, 1);
INSERT INTO `permission_relationships` VALUES (527, 1);
INSERT INTO `permission_relationships` VALUES (528, 1);
INSERT INTO `permission_relationships` VALUES (529, 1);
INSERT INTO `permission_relationships` VALUES (530, 1);
INSERT INTO `permission_relationships` VALUES (531, 1);
INSERT INTO `permission_relationships` VALUES (532, 1);
INSERT INTO `permission_relationships` VALUES (534, 1);
INSERT INTO `permission_relationships` VALUES (535, 1);
INSERT INTO `permission_relationships` VALUES (536, 1);
INSERT INTO `permission_relationships` VALUES (537, 1);
INSERT INTO `permission_relationships` VALUES (538, 1);
INSERT INTO `permission_relationships` VALUES (539, 1);
INSERT INTO `permission_relationships` VALUES (540, 1);
INSERT INTO `permission_relationships` VALUES (541, 1);
INSERT INTO `permission_relationships` VALUES (542, 1);
INSERT INTO `permission_relationships` VALUES (543, 1);
INSERT INTO `permission_relationships` VALUES (544, 1);
INSERT INTO `permission_relationships` VALUES (545, 1);
INSERT INTO `permission_relationships` VALUES (546, 1);
INSERT INTO `permission_relationships` VALUES (547, 1);
INSERT INTO `permission_relationships` VALUES (548, 1);
INSERT INTO `permission_relationships` VALUES (549, 1);
INSERT INTO `permission_relationships` VALUES (550, 1);
INSERT INTO `permission_relationships` VALUES (551, 1);
INSERT INTO `permission_relationships` VALUES (552, 1);
INSERT INTO `permission_relationships` VALUES (553, 1);
INSERT INTO `permission_relationships` VALUES (554, 1);
INSERT INTO `permission_relationships` VALUES (555, 1);
INSERT INTO `permission_relationships` VALUES (556, 1);
INSERT INTO `permission_relationships` VALUES (557, 1);
INSERT INTO `permission_relationships` VALUES (558, 1);
INSERT INTO `permission_relationships` VALUES (559, 1);
INSERT INTO `permission_relationships` VALUES (560, 1);
INSERT INTO `permission_relationships` VALUES (561, 1);
INSERT INTO `permission_relationships` VALUES (562, 1);
INSERT INTO `permission_relationships` VALUES (563, 1);
INSERT INTO `permission_relationships` VALUES (564, 1);
INSERT INTO `permission_relationships` VALUES (565, 1);
INSERT INTO `permission_relationships` VALUES (566, 1);
INSERT INTO `permission_relationships` VALUES (567, 1);
INSERT INTO `permission_relationships` VALUES (568, 1);
INSERT INTO `permission_relationships` VALUES (569, 1);
INSERT INTO `permission_relationships` VALUES (570, 1);
INSERT INTO `permission_relationships` VALUES (571, 1);
INSERT INTO `permission_relationships` VALUES (572, 1);
INSERT INTO `permission_relationships` VALUES (573, 1);
INSERT INTO `permission_relationships` VALUES (574, 1);
INSERT INTO `permission_relationships` VALUES (575, 1);
INSERT INTO `permission_relationships` VALUES (576, 1);
INSERT INTO `permission_relationships` VALUES (577, 1);
INSERT INTO `permission_relationships` VALUES (578, 1);
INSERT INTO `permission_relationships` VALUES (579, 1);
INSERT INTO `permission_relationships` VALUES (580, 1);
INSERT INTO `permission_relationships` VALUES (581, 1);
INSERT INTO `permission_relationships` VALUES (582, 1);
INSERT INTO `permission_relationships` VALUES (583, 1);
INSERT INTO `permission_relationships` VALUES (584, 1);
INSERT INTO `permission_relationships` VALUES (585, 1);
INSERT INTO `permission_relationships` VALUES (586, 1);
INSERT INTO `permission_relationships` VALUES (587, 1);
INSERT INTO `permission_relationships` VALUES (588, 1);
INSERT INTO `permission_relationships` VALUES (589, 1);
INSERT INTO `permission_relationships` VALUES (590, 1);
INSERT INTO `permission_relationships` VALUES (591, 1);
INSERT INTO `permission_relationships` VALUES (592, 1);
INSERT INTO `permission_relationships` VALUES (593, 1);
INSERT INTO `permission_relationships` VALUES (594, 1);
INSERT INTO `permission_relationships` VALUES (595, 1);
INSERT INTO `permission_relationships` VALUES (596, 1);
INSERT INTO `permission_relationships` VALUES (597, 1);
INSERT INTO `permission_relationships` VALUES (598, 1);
INSERT INTO `permission_relationships` VALUES (599, 1);
INSERT INTO `permission_relationships` VALUES (600, 1);
INSERT INTO `permission_relationships` VALUES (601, 1);
INSERT INTO `permission_relationships` VALUES (602, 1);
INSERT INTO `permission_relationships` VALUES (603, 1);
INSERT INTO `permission_relationships` VALUES (604, 1);
INSERT INTO `permission_relationships` VALUES (605, 1);
INSERT INTO `permission_relationships` VALUES (606, 1);
INSERT INTO `permission_relationships` VALUES (607, 1);
INSERT INTO `permission_relationships` VALUES (608, 1);
INSERT INTO `permission_relationships` VALUES (609, 1);
INSERT INTO `permission_relationships` VALUES (610, 1);
INSERT INTO `permission_relationships` VALUES (611, 1);
INSERT INTO `permission_relationships` VALUES (612, 1);
INSERT INTO `permission_relationships` VALUES (613, 1);
INSERT INTO `permission_relationships` VALUES (614, 1);
INSERT INTO `permission_relationships` VALUES (615, 1);
INSERT INTO `permission_relationships` VALUES (616, 1);
INSERT INTO `permission_relationships` VALUES (617, 1);
INSERT INTO `permission_relationships` VALUES (618, 1);
INSERT INTO `permission_relationships` VALUES (619, 1);
INSERT INTO `permission_relationships` VALUES (620, 1);
INSERT INTO `permission_relationships` VALUES (621, 1);
INSERT INTO `permission_relationships` VALUES (622, 1);
INSERT INTO `permission_relationships` VALUES (623, 1);
INSERT INTO `permission_relationships` VALUES (624, 1);
INSERT INTO `permission_relationships` VALUES (625, 1);
INSERT INTO `permission_relationships` VALUES (626, 1);
INSERT INTO `permission_relationships` VALUES (627, 1);
INSERT INTO `permission_relationships` VALUES (628, 1);
INSERT INTO `permission_relationships` VALUES (629, 1);
INSERT INTO `permission_relationships` VALUES (630, 1);
INSERT INTO `permission_relationships` VALUES (631, 1);
INSERT INTO `permission_relationships` VALUES (632, 1);
INSERT INTO `permission_relationships` VALUES (633, 1);
INSERT INTO `permission_relationships` VALUES (634, 1);
INSERT INTO `permission_relationships` VALUES (635, 1);
INSERT INTO `permission_relationships` VALUES (636, 1);
INSERT INTO `permission_relationships` VALUES (637, 1);
INSERT INTO `permission_relationships` VALUES (638, 1);
INSERT INTO `permission_relationships` VALUES (639, 1);
INSERT INTO `permission_relationships` VALUES (640, 1);
INSERT INTO `permission_relationships` VALUES (641, 1);
INSERT INTO `permission_relationships` VALUES (642, 1);
INSERT INTO `permission_relationships` VALUES (643, 1);
INSERT INTO `permission_relationships` VALUES (644, 1);
INSERT INTO `permission_relationships` VALUES (645, 1);
INSERT INTO `permission_relationships` VALUES (646, 1);
INSERT INTO `permission_relationships` VALUES (647, 1);
INSERT INTO `permission_relationships` VALUES (648, 1);
INSERT INTO `permission_relationships` VALUES (649, 1);
INSERT INTO `permission_relationships` VALUES (650, 1);
INSERT INTO `permission_relationships` VALUES (651, 1);
INSERT INTO `permission_relationships` VALUES (652, 1);
INSERT INTO `permission_relationships` VALUES (653, 1);
INSERT INTO `permission_relationships` VALUES (654, 1);
INSERT INTO `permission_relationships` VALUES (655, 1);
INSERT INTO `permission_relationships` VALUES (656, 1);
INSERT INTO `permission_relationships` VALUES (657, 1);
INSERT INTO `permission_relationships` VALUES (658, 1);
INSERT INTO `permission_relationships` VALUES (659, 1);
INSERT INTO `permission_relationships` VALUES (660, 1);
INSERT INTO `permission_relationships` VALUES (661, 1);
INSERT INTO `permission_relationships` VALUES (662, 1);
INSERT INTO `permission_relationships` VALUES (663, 1);
INSERT INTO `permission_relationships` VALUES (664, 1);
INSERT INTO `permission_relationships` VALUES (665, 1);
INSERT INTO `permission_relationships` VALUES (666, 1);
INSERT INTO `permission_relationships` VALUES (667, 1);
INSERT INTO `permission_relationships` VALUES (668, 1);
INSERT INTO `permission_relationships` VALUES (669, 1);
INSERT INTO `permission_relationships` VALUES (670, 1);
INSERT INTO `permission_relationships` VALUES (671, 1);
INSERT INTO `permission_relationships` VALUES (672, 1);
INSERT INTO `permission_relationships` VALUES (673, 1);
INSERT INTO `permission_relationships` VALUES (674, 1);
INSERT INTO `permission_relationships` VALUES (675, 1);
INSERT INTO `permission_relationships` VALUES (676, 1);
INSERT INTO `permission_relationships` VALUES (677, 1);
INSERT INTO `permission_relationships` VALUES (678, 1);
INSERT INTO `permission_relationships` VALUES (679, 1);
INSERT INTO `permission_relationships` VALUES (680, 1);
INSERT INTO `permission_relationships` VALUES (681, 1);
INSERT INTO `permission_relationships` VALUES (682, 1);
INSERT INTO `permission_relationships` VALUES (683, 1);
INSERT INTO `permission_relationships` VALUES (684, 1);
INSERT INTO `permission_relationships` VALUES (685, 1);
INSERT INTO `permission_relationships` VALUES (686, 1);
INSERT INTO `permission_relationships` VALUES (687, 1);
INSERT INTO `permission_relationships` VALUES (688, 1);
INSERT INTO `permission_relationships` VALUES (689, 1);
INSERT INTO `permission_relationships` VALUES (690, 1);
INSERT INTO `permission_relationships` VALUES (691, 1);
INSERT INTO `permission_relationships` VALUES (692, 1);
INSERT INTO `permission_relationships` VALUES (693, 1);
INSERT INTO `permission_relationships` VALUES (694, 1);
INSERT INTO `permission_relationships` VALUES (695, 1);
INSERT INTO `permission_relationships` VALUES (696, 1);
INSERT INTO `permission_relationships` VALUES (697, 1);
INSERT INTO `permission_relationships` VALUES (698, 1);
INSERT INTO `permission_relationships` VALUES (699, 1);
INSERT INTO `permission_relationships` VALUES (700, 1);
INSERT INTO `permission_relationships` VALUES (701, 1);
INSERT INTO `permission_relationships` VALUES (702, 1);
INSERT INTO `permission_relationships` VALUES (703, 1);
INSERT INTO `permission_relationships` VALUES (704, 1);
INSERT INTO `permission_relationships` VALUES (705, 1);
INSERT INTO `permission_relationships` VALUES (706, 1);
INSERT INTO `permission_relationships` VALUES (707, 1);
INSERT INTO `permission_relationships` VALUES (708, 1);
INSERT INTO `permission_relationships` VALUES (709, 1);
INSERT INTO `permission_relationships` VALUES (710, 1);
INSERT INTO `permission_relationships` VALUES (711, 1);
INSERT INTO `permission_relationships` VALUES (712, 1);
INSERT INTO `permission_relationships` VALUES (713, 1);
INSERT INTO `permission_relationships` VALUES (714, 1);
INSERT INTO `permission_relationships` VALUES (715, 1);
INSERT INTO `permission_relationships` VALUES (716, 1);
INSERT INTO `permission_relationships` VALUES (717, 1);
INSERT INTO `permission_relationships` VALUES (718, 1);
INSERT INTO `permission_relationships` VALUES (719, 1);
INSERT INTO `permission_relationships` VALUES (720, 1);
INSERT INTO `permission_relationships` VALUES (721, 1);
INSERT INTO `permission_relationships` VALUES (722, 1);
INSERT INTO `permission_relationships` VALUES (723, 1);
INSERT INTO `permission_relationships` VALUES (724, 1);
INSERT INTO `permission_relationships` VALUES (725, 1);
INSERT INTO `permission_relationships` VALUES (726, 1);
INSERT INTO `permission_relationships` VALUES (727, 1);
INSERT INTO `permission_relationships` VALUES (728, 1);
INSERT INTO `permission_relationships` VALUES (729, 1);
INSERT INTO `permission_relationships` VALUES (730, 1);
INSERT INTO `permission_relationships` VALUES (731, 1);
INSERT INTO `permission_relationships` VALUES (732, 1);
INSERT INTO `permission_relationships` VALUES (733, 1);
INSERT INTO `permission_relationships` VALUES (734, 1);
INSERT INTO `permission_relationships` VALUES (735, 1);
INSERT INTO `permission_relationships` VALUES (736, 1);
INSERT INTO `permission_relationships` VALUES (737, 1);
INSERT INTO `permission_relationships` VALUES (738, 1);
INSERT INTO `permission_relationships` VALUES (739, 1);
INSERT INTO `permission_relationships` VALUES (740, 1);
INSERT INTO `permission_relationships` VALUES (741, 1);
INSERT INTO `permission_relationships` VALUES (742, 1);
INSERT INTO `permission_relationships` VALUES (743, 1);
INSERT INTO `permission_relationships` VALUES (744, 1);
INSERT INTO `permission_relationships` VALUES (745, 1);
INSERT INTO `permission_relationships` VALUES (746, 1);
INSERT INTO `permission_relationships` VALUES (747, 1);
INSERT INTO `permission_relationships` VALUES (748, 1);
INSERT INTO `permission_relationships` VALUES (749, 1);
INSERT INTO `permission_relationships` VALUES (750, 1);
INSERT INTO `permission_relationships` VALUES (751, 1);
INSERT INTO `permission_relationships` VALUES (752, 1);
INSERT INTO `permission_relationships` VALUES (753, 1);
INSERT INTO `permission_relationships` VALUES (754, 1);
INSERT INTO `permission_relationships` VALUES (755, 1);
INSERT INTO `permission_relationships` VALUES (756, 1);
INSERT INTO `permission_relationships` VALUES (757, 1);
INSERT INTO `permission_relationships` VALUES (758, 1);
INSERT INTO `permission_relationships` VALUES (759, 1);
INSERT INTO `permission_relationships` VALUES (760, 1);
INSERT INTO `permission_relationships` VALUES (761, 1);
INSERT INTO `permission_relationships` VALUES (762, 1);
INSERT INTO `permission_relationships` VALUES (763, 1);
INSERT INTO `permission_relationships` VALUES (764, 1);
INSERT INTO `permission_relationships` VALUES (765, 1);
INSERT INTO `permission_relationships` VALUES (766, 1);
INSERT INTO `permission_relationships` VALUES (767, 1);
INSERT INTO `permission_relationships` VALUES (768, 1);
INSERT INTO `permission_relationships` VALUES (769, 1);
INSERT INTO `permission_relationships` VALUES (770, 1);
INSERT INTO `permission_relationships` VALUES (771, 1);
INSERT INTO `permission_relationships` VALUES (772, 1);
INSERT INTO `permission_relationships` VALUES (773, 1);
INSERT INTO `permission_relationships` VALUES (774, 1);
INSERT INTO `permission_relationships` VALUES (775, 1);
INSERT INTO `permission_relationships` VALUES (776, 1);
INSERT INTO `permission_relationships` VALUES (777, 1);
INSERT INTO `permission_relationships` VALUES (778, 1);
INSERT INTO `permission_relationships` VALUES (779, 1);
INSERT INTO `permission_relationships` VALUES (780, 1);
INSERT INTO `permission_relationships` VALUES (781, 1);
INSERT INTO `permission_relationships` VALUES (782, 1);
INSERT INTO `permission_relationships` VALUES (783, 1);
INSERT INTO `permission_relationships` VALUES (784, 1);
INSERT INTO `permission_relationships` VALUES (785, 1);
INSERT INTO `permission_relationships` VALUES (786, 1);
INSERT INTO `permission_relationships` VALUES (787, 1);
INSERT INTO `permission_relationships` VALUES (788, 1);
INSERT INTO `permission_relationships` VALUES (789, 1);
INSERT INTO `permission_relationships` VALUES (790, 1);
INSERT INTO `permission_relationships` VALUES (791, 1);
INSERT INTO `permission_relationships` VALUES (792, 1);
INSERT INTO `permission_relationships` VALUES (793, 1);
INSERT INTO `permission_relationships` VALUES (794, 1);
INSERT INTO `permission_relationships` VALUES (795, 1);
INSERT INTO `permission_relationships` VALUES (796, 1);
INSERT INTO `permission_relationships` VALUES (797, 1);
INSERT INTO `permission_relationships` VALUES (798, 1);
INSERT INTO `permission_relationships` VALUES (799, 1);
INSERT INTO `permission_relationships` VALUES (800, 1);
INSERT INTO `permission_relationships` VALUES (801, 1);
INSERT INTO `permission_relationships` VALUES (802, 1);
INSERT INTO `permission_relationships` VALUES (803, 1);
INSERT INTO `permission_relationships` VALUES (501, 3);
INSERT INTO `permission_relationships` VALUES (512, 3);
INSERT INTO `permission_relationships` VALUES (526, 3);
INSERT INTO `permission_relationships` VALUES (539, 3);
INSERT INTO `permission_relationships` VALUES (543, 3);
INSERT INTO `permission_relationships` VALUES (544, 3);
INSERT INTO `permission_relationships` VALUES (548, 3);
INSERT INTO `permission_relationships` VALUES (561, 3);
INSERT INTO `permission_relationships` VALUES (571, 3);
INSERT INTO `permission_relationships` VALUES (579, 3);
INSERT INTO `permission_relationships` VALUES (580, 3);
INSERT INTO `permission_relationships` VALUES (653, 3);
INSERT INTO `permission_relationships` VALUES (660, 3);
INSERT INTO `permission_relationships` VALUES (665, 3);
INSERT INTO `permission_relationships` VALUES (669, 3);
INSERT INTO `permission_relationships` VALUES (672, 3);
INSERT INTO `permission_relationships` VALUES (673, 3);
INSERT INTO `permission_relationships` VALUES (677, 3);
INSERT INTO `permission_relationships` VALUES (682, 3);
INSERT INTO `permission_relationships` VALUES (686, 3);
INSERT INTO `permission_relationships` VALUES (690, 3);
INSERT INTO `permission_relationships` VALUES (699, 3);
INSERT INTO `permission_relationships` VALUES (703, 3);
INSERT INTO `permission_relationships` VALUES (704, 3);
INSERT INTO `permission_relationships` VALUES (716, 3);
INSERT INTO `permission_relationships` VALUES (720, 3);
INSERT INTO `permission_relationships` VALUES (721, 3);
INSERT INTO `permission_relationships` VALUES (725, 3);
INSERT INTO `permission_relationships` VALUES (726, 3);
INSERT INTO `permission_relationships` VALUES (730, 3);
INSERT INTO `permission_relationships` VALUES (762, 3);
INSERT INTO `permission_relationships` VALUES (763, 3);
INSERT INTO `permission_relationships` VALUES (501, 4);
INSERT INTO `permission_relationships` VALUES (512, 4);
INSERT INTO `permission_relationships` VALUES (516, 4);
INSERT INTO `permission_relationships` VALUES (526, 4);
INSERT INTO `permission_relationships` VALUES (535, 4);
INSERT INTO `permission_relationships` VALUES (544, 4);
INSERT INTO `permission_relationships` VALUES (548, 4);
INSERT INTO `permission_relationships` VALUES (550, 4);
INSERT INTO `permission_relationships` VALUES (561, 4);
INSERT INTO `permission_relationships` VALUES (571, 4);
INSERT INTO `permission_relationships` VALUES (573, 4);
INSERT INTO `permission_relationships` VALUES (579, 4);
INSERT INTO `permission_relationships` VALUES (580, 4);
INSERT INTO `permission_relationships` VALUES (653, 4);
INSERT INTO `permission_relationships` VALUES (656, 4);
INSERT INTO `permission_relationships` VALUES (660, 4);
INSERT INTO `permission_relationships` VALUES (664, 4);
INSERT INTO `permission_relationships` VALUES (665, 4);
INSERT INTO `permission_relationships` VALUES (669, 4);
INSERT INTO `permission_relationships` VALUES (672, 4);
INSERT INTO `permission_relationships` VALUES (673, 4);
INSERT INTO `permission_relationships` VALUES (677, 4);
INSERT INTO `permission_relationships` VALUES (681, 4);
INSERT INTO `permission_relationships` VALUES (682, 4);
INSERT INTO `permission_relationships` VALUES (686, 4);
INSERT INTO `permission_relationships` VALUES (690, 4);
INSERT INTO `permission_relationships` VALUES (694, 4);
INSERT INTO `permission_relationships` VALUES (699, 4);
INSERT INTO `permission_relationships` VALUES (703, 4);
INSERT INTO `permission_relationships` VALUES (704, 4);
INSERT INTO `permission_relationships` VALUES (716, 4);
INSERT INTO `permission_relationships` VALUES (720, 4);
INSERT INTO `permission_relationships` VALUES (721, 4);
INSERT INTO `permission_relationships` VALUES (725, 4);
INSERT INTO `permission_relationships` VALUES (726, 4);
INSERT INTO `permission_relationships` VALUES (730, 4);
INSERT INTO `permission_relationships` VALUES (762, 4);
INSERT INTO `permission_relationships` VALUES (763, 4);
INSERT INTO `permission_relationships` VALUES (501, 5);
INSERT INTO `permission_relationships` VALUES (512, 5);
INSERT INTO `permission_relationships` VALUES (516, 5);
INSERT INTO `permission_relationships` VALUES (554, 5);
INSERT INTO `permission_relationships` VALUES (556, 5);
INSERT INTO `permission_relationships` VALUES (579, 5);
INSERT INTO `permission_relationships` VALUES (580, 5);
INSERT INTO `permission_relationships` VALUES (608, 5);
INSERT INTO `permission_relationships` VALUES (609, 5);
INSERT INTO `permission_relationships` VALUES (610, 5);
INSERT INTO `permission_relationships` VALUES (611, 5);
INSERT INTO `permission_relationships` VALUES (612, 5);
INSERT INTO `permission_relationships` VALUES (613, 5);
INSERT INTO `permission_relationships` VALUES (614, 5);
INSERT INTO `permission_relationships` VALUES (615, 5);
INSERT INTO `permission_relationships` VALUES (616, 5);
INSERT INTO `permission_relationships` VALUES (617, 5);
INSERT INTO `permission_relationships` VALUES (618, 5);
INSERT INTO `permission_relationships` VALUES (619, 5);
INSERT INTO `permission_relationships` VALUES (620, 5);
INSERT INTO `permission_relationships` VALUES (621, 5);
INSERT INTO `permission_relationships` VALUES (622, 5);
INSERT INTO `permission_relationships` VALUES (673, 5);
INSERT INTO `permission_relationships` VALUES (677, 5);
INSERT INTO `permission_relationships` VALUES (678, 5);
INSERT INTO `permission_relationships` VALUES (679, 5);
INSERT INTO `permission_relationships` VALUES (680, 5);
INSERT INTO `permission_relationships` VALUES (681, 5);
INSERT INTO `permission_relationships` VALUES (682, 5);
INSERT INTO `permission_relationships` VALUES (686, 5);
INSERT INTO `permission_relationships` VALUES (690, 5);
INSERT INTO `permission_relationships` VALUES (691, 5);
INSERT INTO `permission_relationships` VALUES (692, 5);
INSERT INTO `permission_relationships` VALUES (693, 5);
INSERT INTO `permission_relationships` VALUES (694, 5);
INSERT INTO `permission_relationships` VALUES (695, 5);
INSERT INTO `permission_relationships` VALUES (696, 5);
INSERT INTO `permission_relationships` VALUES (697, 5);
INSERT INTO `permission_relationships` VALUES (698, 5);
INSERT INTO `permission_relationships` VALUES (699, 5);
INSERT INTO `permission_relationships` VALUES (700, 5);
INSERT INTO `permission_relationships` VALUES (701, 5);
INSERT INTO `permission_relationships` VALUES (702, 5);
INSERT INTO `permission_relationships` VALUES (703, 5);
INSERT INTO `permission_relationships` VALUES (704, 5);
INSERT INTO `permission_relationships` VALUES (705, 5);
INSERT INTO `permission_relationships` VALUES (706, 5);
INSERT INTO `permission_relationships` VALUES (707, 5);
INSERT INTO `permission_relationships` VALUES (708, 5);
INSERT INTO `permission_relationships` VALUES (709, 5);
INSERT INTO `permission_relationships` VALUES (710, 5);
INSERT INTO `permission_relationships` VALUES (711, 5);
INSERT INTO `permission_relationships` VALUES (712, 5);
INSERT INTO `permission_relationships` VALUES (713, 5);
INSERT INTO `permission_relationships` VALUES (714, 5);
INSERT INTO `permission_relationships` VALUES (715, 5);
INSERT INTO `permission_relationships` VALUES (716, 5);
INSERT INTO `permission_relationships` VALUES (720, 5);
INSERT INTO `permission_relationships` VALUES (721, 5);
INSERT INTO `permission_relationships` VALUES (725, 5);
INSERT INTO `permission_relationships` VALUES (726, 5);
INSERT INTO `permission_relationships` VALUES (730, 5);
INSERT INTO `permission_relationships` VALUES (746, 5);
INSERT INTO `permission_relationships` VALUES (747, 5);
INSERT INTO `permission_relationships` VALUES (748, 5);
INSERT INTO `permission_relationships` VALUES (749, 5);
INSERT INTO `permission_relationships` VALUES (750, 5);
INSERT INTO `permission_relationships` VALUES (762, 5);
INSERT INTO `permission_relationships` VALUES (763, 5);
INSERT INTO `permission_relationships` VALUES (501, 2);
INSERT INTO `permission_relationships` VALUES (502, 2);
INSERT INTO `permission_relationships` VALUES (506, 2);
INSERT INTO `permission_relationships` VALUES (507, 2);
INSERT INTO `permission_relationships` VALUES (511, 2);
INSERT INTO `permission_relationships` VALUES (512, 2);
INSERT INTO `permission_relationships` VALUES (516, 2);
INSERT INTO `permission_relationships` VALUES (526, 2);
INSERT INTO `permission_relationships` VALUES (535, 2);
INSERT INTO `permission_relationships` VALUES (536, 2);
INSERT INTO `permission_relationships` VALUES (537, 2);
INSERT INTO `permission_relationships` VALUES (538, 2);
INSERT INTO `permission_relationships` VALUES (539, 2);
INSERT INTO `permission_relationships` VALUES (540, 2);
INSERT INTO `permission_relationships` VALUES (541, 2);
INSERT INTO `permission_relationships` VALUES (542, 2);
INSERT INTO `permission_relationships` VALUES (543, 2);
INSERT INTO `permission_relationships` VALUES (544, 2);
INSERT INTO `permission_relationships` VALUES (548, 2);
INSERT INTO `permission_relationships` VALUES (549, 2);
INSERT INTO `permission_relationships` VALUES (550, 2);
INSERT INTO `permission_relationships` VALUES (551, 2);
INSERT INTO `permission_relationships` VALUES (553, 2);
INSERT INTO `permission_relationships` VALUES (554, 2);
INSERT INTO `permission_relationships` VALUES (556, 2);
INSERT INTO `permission_relationships` VALUES (561, 2);
INSERT INTO `permission_relationships` VALUES (569, 2);
INSERT INTO `permission_relationships` VALUES (570, 2);
INSERT INTO `permission_relationships` VALUES (571, 2);
INSERT INTO `permission_relationships` VALUES (572, 2);
INSERT INTO `permission_relationships` VALUES (573, 2);
INSERT INTO `permission_relationships` VALUES (579, 2);
INSERT INTO `permission_relationships` VALUES (580, 2);
INSERT INTO `permission_relationships` VALUES (581, 2);
INSERT INTO `permission_relationships` VALUES (582, 2);
INSERT INTO `permission_relationships` VALUES (586, 2);
INSERT INTO `permission_relationships` VALUES (587, 2);
INSERT INTO `permission_relationships` VALUES (588, 2);
INSERT INTO `permission_relationships` VALUES (590, 2);
INSERT INTO `permission_relationships` VALUES (591, 2);
INSERT INTO `permission_relationships` VALUES (592, 2);
INSERT INTO `permission_relationships` VALUES (594, 2);
INSERT INTO `permission_relationships` VALUES (595, 2);
INSERT INTO `permission_relationships` VALUES (596, 2);
INSERT INTO `permission_relationships` VALUES (598, 2);
INSERT INTO `permission_relationships` VALUES (599, 2);
INSERT INTO `permission_relationships` VALUES (600, 2);
INSERT INTO `permission_relationships` VALUES (601, 2);
INSERT INTO `permission_relationships` VALUES (603, 2);
INSERT INTO `permission_relationships` VALUES (604, 2);
INSERT INTO `permission_relationships` VALUES (605, 2);
INSERT INTO `permission_relationships` VALUES (607, 2);
INSERT INTO `permission_relationships` VALUES (653, 2);
INSERT INTO `permission_relationships` VALUES (654, 2);
INSERT INTO `permission_relationships` VALUES (655, 2);
INSERT INTO `permission_relationships` VALUES (665, 2);
INSERT INTO `permission_relationships` VALUES (673, 2);
INSERT INTO `permission_relationships` VALUES (682, 2);
INSERT INTO `permission_relationships` VALUES (686, 2);
INSERT INTO `permission_relationships` VALUES (716, 2);
INSERT INTO `permission_relationships` VALUES (720, 2);
INSERT INTO `permission_relationships` VALUES (721, 2);
INSERT INTO `permission_relationships` VALUES (725, 2);
INSERT INTO `permission_relationships` VALUES (726, 2);
INSERT INTO `permission_relationships` VALUES (730, 2);
INSERT INTO `permission_relationships` VALUES (732, 2);
INSERT INTO `permission_relationships` VALUES (735, 2);
INSERT INTO `permission_relationships` VALUES (736, 2);
INSERT INTO `permission_relationships` VALUES (737, 2);
INSERT INTO `permission_relationships` VALUES (738, 2);
INSERT INTO `permission_relationships` VALUES (739, 2);
INSERT INTO `permission_relationships` VALUES (740, 2);
INSERT INTO `permission_relationships` VALUES (741, 2);
INSERT INTO `permission_relationships` VALUES (742, 2);
INSERT INTO `permission_relationships` VALUES (743, 2);
INSERT INTO `permission_relationships` VALUES (744, 2);
INSERT INTO `permission_relationships` VALUES (762, 2);
INSERT INTO `permission_relationships` VALUES (763, 2);
INSERT INTO `permission_relationships` VALUES (501, 6);
INSERT INTO `permission_relationships` VALUES (512, 6);
INSERT INTO `permission_relationships` VALUES (516, 6);
INSERT INTO `permission_relationships` VALUES (526, 6);
INSERT INTO `permission_relationships` VALUES (554, 6);
INSERT INTO `permission_relationships` VALUES (556, 6);
INSERT INTO `permission_relationships` VALUES (579, 6);
INSERT INTO `permission_relationships` VALUES (580, 6);
INSERT INTO `permission_relationships` VALUES (660, 6);
INSERT INTO `permission_relationships` VALUES (661, 6);
INSERT INTO `permission_relationships` VALUES (662, 6);
INSERT INTO `permission_relationships` VALUES (663, 6);
INSERT INTO `permission_relationships` VALUES (664, 6);
INSERT INTO `permission_relationships` VALUES (665, 6);
INSERT INTO `permission_relationships` VALUES (666, 6);
INSERT INTO `permission_relationships` VALUES (667, 6);
INSERT INTO `permission_relationships` VALUES (668, 6);
INSERT INTO `permission_relationships` VALUES (669, 6);
INSERT INTO `permission_relationships` VALUES (670, 6);
INSERT INTO `permission_relationships` VALUES (671, 6);
INSERT INTO `permission_relationships` VALUES (672, 6);
INSERT INTO `permission_relationships` VALUES (673, 6);
INSERT INTO `permission_relationships` VALUES (682, 6);
INSERT INTO `permission_relationships` VALUES (686, 6);
INSERT INTO `permission_relationships` VALUES (716, 6);
INSERT INTO `permission_relationships` VALUES (720, 6);
INSERT INTO `permission_relationships` VALUES (721, 6);
INSERT INTO `permission_relationships` VALUES (725, 6);
INSERT INTO `permission_relationships` VALUES (726, 6);
INSERT INTO `permission_relationships` VALUES (730, 6);
INSERT INTO `permission_relationships` VALUES (732, 6);
INSERT INTO `permission_relationships` VALUES (762, 6);
INSERT INTO `permission_relationships` VALUES (763, 6);
INSERT INTO `permission_relationships` VALUES (501, 7);
INSERT INTO `permission_relationships` VALUES (502, 7);
INSERT INTO `permission_relationships` VALUES (506, 7);
INSERT INTO `permission_relationships` VALUES (507, 7);
INSERT INTO `permission_relationships` VALUES (511, 7);
INSERT INTO `permission_relationships` VALUES (512, 7);
INSERT INTO `permission_relationships` VALUES (516, 7);
INSERT INTO `permission_relationships` VALUES (517, 7);
INSERT INTO `permission_relationships` VALUES (521, 7);
INSERT INTO `permission_relationships` VALUES (554, 7);
INSERT INTO `permission_relationships` VALUES (556, 7);
INSERT INTO `permission_relationships` VALUES (579, 7);
INSERT INTO `permission_relationships` VALUES (580, 7);
INSERT INTO `permission_relationships` VALUES (682, 7);
INSERT INTO `permission_relationships` VALUES (686, 7);
INSERT INTO `permission_relationships` VALUES (690, 7);
INSERT INTO `permission_relationships` VALUES (694, 7);
INSERT INTO `permission_relationships` VALUES (716, 7);
INSERT INTO `permission_relationships` VALUES (720, 7);
INSERT INTO `permission_relationships` VALUES (721, 7);
INSERT INTO `permission_relationships` VALUES (725, 7);
INSERT INTO `permission_relationships` VALUES (726, 7);
INSERT INTO `permission_relationships` VALUES (730, 7);
INSERT INTO `permission_relationships` VALUES (751, 7);
INSERT INTO `permission_relationships` VALUES (752, 7);
INSERT INTO `permission_relationships` VALUES (753, 7);
INSERT INTO `permission_relationships` VALUES (762, 7);
INSERT INTO `permission_relationships` VALUES (763, 7);
INSERT INTO `permission_relationships` VALUES (805, 1);
INSERT INTO `permission_relationships` VALUES (804, 1);
INSERT INTO `permission_relationships` VALUES (805, 2);
INSERT INTO `permission_relationships` VALUES (804, 2);
INSERT INTO `permission_relationships` VALUES (805, 3);
INSERT INTO `permission_relationships` VALUES (804, 3);
INSERT INTO `permission_relationships` VALUES (805, 4);
INSERT INTO `permission_relationships` VALUES (804, 4);
INSERT INTO `permission_relationships` VALUES (805, 5);
INSERT INTO `permission_relationships` VALUES (804, 5);


-- ----------------------------
-- Records of permissions
-- ----------------------------
INSERT INTO `permissions` VALUES (501, 'Dashboard', 'dashboard', 'yes');
INSERT INTO `permissions` VALUES (502, 'Student', 'student', 'yes');
INSERT INTO `permissions` VALUES (503, 'Student Add', 'student_add', 'yes');
INSERT INTO `permissions` VALUES (504, 'Student Edit', 'student_edit', 'yes');
INSERT INTO `permissions` VALUES (505, 'Student Delete', 'student_delete', 'yes');
INSERT INTO `permissions` VALUES (506, 'Student View', 'student_view', 'yes');
INSERT INTO `permissions` VALUES (507, 'Parents', 'parents', 'yes');
INSERT INTO `permissions` VALUES (508, 'Parents Add', 'parents_add', 'yes');
INSERT INTO `permissions` VALUES (509, 'Parents Edit', 'parents_edit', 'yes');
INSERT INTO `permissions` VALUES (510, 'Parents Delete', 'parents_delete', 'yes');
INSERT INTO `permissions` VALUES (511, 'Parents View', 'parents_view', 'yes');
INSERT INTO `permissions` VALUES (512, 'Teacher', 'teacher', 'yes');
INSERT INTO `permissions` VALUES (513, 'Teacher Add', 'teacher_add', 'yes');
INSERT INTO `permissions` VALUES (514, 'Teacher Edit', 'teacher_edit', 'yes');
INSERT INTO `permissions` VALUES (515, 'Teacher Delete', 'teacher_delete', 'yes');
INSERT INTO `permissions` VALUES (516, 'Teacher View', 'teacher_view', 'yes');
INSERT INTO `permissions` VALUES (517, 'User', 'user', 'yes');
INSERT INTO `permissions` VALUES (518, 'User Add', 'user_add', 'yes');
INSERT INTO `permissions` VALUES (519, 'User Edit', 'user_edit', 'yes');
INSERT INTO `permissions` VALUES (520, 'User Delete', 'user_delete', 'yes');
INSERT INTO `permissions` VALUES (521, 'User View', 'user_view', 'yes');
INSERT INTO `permissions` VALUES (522, 'Class', 'classes', 'yes');
INSERT INTO `permissions` VALUES (523, 'Class Add', 'classes_add', 'yes');
INSERT INTO `permissions` VALUES (524, 'Class Edit', 'classes_edit', 'yes');
INSERT INTO `permissions` VALUES (525, 'Class Delete', 'classes_delete', 'yes');
INSERT INTO `permissions` VALUES (526, 'Subject', 'subject', 'yes');
INSERT INTO `permissions` VALUES (527, 'Subject Add', 'subject_add', 'yes');
INSERT INTO `permissions` VALUES (528, 'Subject Edit', 'subject_edit', 'yes');
INSERT INTO `permissions` VALUES (529, 'Subject Delete', 'subject_delete', 'yes');
INSERT INTO `permissions` VALUES (530, 'Section', 'section', 'yes');
INSERT INTO `permissions` VALUES (531, 'Section Add', 'section_add', 'yes');
INSERT INTO `permissions` VALUES (532, 'Section Edit', 'section_edit', 'yes');
INSERT INTO `permissions` VALUES (533, 'Semester Delete', 'semester_delete', 'yes');
INSERT INTO `permissions` VALUES (534, 'Section Delete', 'section_delete', 'yes');
INSERT INTO `permissions` VALUES (535, 'Syllabus', 'syllabus', 'yes');
INSERT INTO `permissions` VALUES (536, 'Syllabus Add', 'syllabus_add', 'yes');
INSERT INTO `permissions` VALUES (537, 'Syllabus Edit', 'syllabus_edit', 'yes');
INSERT INTO `permissions` VALUES (538, 'Syllabus Delete', 'syllabus_delete', 'yes');
INSERT INTO `permissions` VALUES (539, 'Assignment', 'assignment', 'yes');
INSERT INTO `permissions` VALUES (540, 'Assignment Add', 'assignment_add', 'yes');
INSERT INTO `permissions` VALUES (541, 'Assignment Edit', 'assignment_edit', 'yes');
INSERT INTO `permissions` VALUES (542, 'Assignment Delete', 'assignment_delete', 'yes');
INSERT INTO `permissions` VALUES (543, 'Assignment View', 'assignment_view', 'yes');
INSERT INTO `permissions` VALUES (544, 'Routine', 'routine', 'yes');
INSERT INTO `permissions` VALUES (545, 'Routine Add', 'routine_add', 'yes');
INSERT INTO `permissions` VALUES (546, 'Routine Edit', 'routine_edit', 'yes');
INSERT INTO `permissions` VALUES (547, 'Routine Delete', 'routine_delete', 'yes');
INSERT INTO `permissions` VALUES (548, 'Student Attendance', 'sattendance', 'yes');
INSERT INTO `permissions` VALUES (549, 'Student Attendance Add', 'sattendance_add', 'yes');
INSERT INTO `permissions` VALUES (550, 'Student Attendance View', 'sattendance_view', 'yes');
INSERT INTO `permissions` VALUES (551, 'Teacher Attendance', 'tattendance', 'yes');
INSERT INTO `permissions` VALUES (552, 'Teacher Attendance Add', 'tattendance_add', 'yes');
INSERT INTO `permissions` VALUES (553, 'Teacher Attendance View', 'tattendance_view', 'yes');
INSERT INTO `permissions` VALUES (554, 'User Attendance', 'uattendance', 'yes');
INSERT INTO `permissions` VALUES (555, 'User Attendance Add', 'uattendance_add', 'yes');
INSERT INTO `permissions` VALUES (556, 'User Attendance View', 'uattendance_view', 'yes');
INSERT INTO `permissions` VALUES (557, 'Exam', 'exam', 'yes');
INSERT INTO `permissions` VALUES (558, 'Exam Add', 'exam_add', 'yes');
INSERT INTO `permissions` VALUES (559, 'Exam Edit', 'exam_edit', 'yes');
INSERT INTO `permissions` VALUES (560, 'Exam Delete', 'exam_delete', 'yes');
INSERT INTO `permissions` VALUES (561, 'Examschedule', 'examschedule', 'yes');
INSERT INTO `permissions` VALUES (562, 'Examschedule Add', 'examschedule_add', 'yes');
INSERT INTO `permissions` VALUES (563, 'Examschedule Edit', 'examschedule_edit', 'yes');
INSERT INTO `permissions` VALUES (564, 'Examschedule Delete', 'examschedule_delete', 'yes');
INSERT INTO `permissions` VALUES (565, 'Grade', 'grade', 'yes');
INSERT INTO `permissions` VALUES (566, 'Grade Add', 'grade_add', 'yes');
INSERT INTO `permissions` VALUES (567, 'Grade Edit', 'grade_edit', 'yes');
INSERT INTO `permissions` VALUES (568, 'Grade Delete', 'grade_delete', 'yes');
INSERT INTO `permissions` VALUES (569, 'Exam Attendance', 'eattendance', 'yes');
INSERT INTO `permissions` VALUES (570, 'Exam Attendance Add', 'eattendance_add', 'yes');
INSERT INTO `permissions` VALUES (571, 'Mark', 'mark', 'yes');
INSERT INTO `permissions` VALUES (572, 'Mark Add', 'mark_add', 'yes');
INSERT INTO `permissions` VALUES (573, 'Mark View', 'mark_view', 'yes');
INSERT INTO `permissions` VALUES (574, 'mark percentage', 'markpercentage', 'yes');
INSERT INTO `permissions` VALUES (575, 'Mark Percentage Add', 'markpercentage_add', 'yes');
INSERT INTO `permissions` VALUES (576, 'Mark Percentage Edit', 'markpercentage_edit', 'yes');
INSERT INTO `permissions` VALUES (577, 'Mark Percentage Delete', 'markpercentage_delete', 'yes');
INSERT INTO `permissions` VALUES (578, 'Promotion', 'promotion', 'yes');
INSERT INTO `permissions` VALUES (579, 'Message', 'conversation', 'yes');
INSERT INTO `permissions` VALUES (580, 'Media', 'media', 'yes');
INSERT INTO `permissions` VALUES (581, 'Media Add', 'media_add', 'yes');
INSERT INTO `permissions` VALUES (582, 'Media Delete', 'media_delete', 'yes');
INSERT INTO `permissions` VALUES (583, 'Mail / SMS', 'mailandsms', 'yes');
INSERT INTO `permissions` VALUES (584, 'Mail / SMS Add', 'mailandsms_add', 'yes');
INSERT INTO `permissions` VALUES (585, 'Mail / SMS View', 'mailandsms_view', 'yes');
INSERT INTO `permissions` VALUES (586, 'Question Group', 'question_group', 'yes');
INSERT INTO `permissions` VALUES (587, 'Question Group Add', 'question_group_add', 'yes');
INSERT INTO `permissions` VALUES (588, 'Question Group Edit', 'question_group_edit', 'yes');
INSERT INTO `permissions` VALUES (589, 'Question Group Delete', 'question_group_delete', 'yes');
INSERT INTO `permissions` VALUES (590, 'Question Level', 'question_level', 'yes');
INSERT INTO `permissions` VALUES (591, 'Question Level Add', 'question_level_add', 'yes');
INSERT INTO `permissions` VALUES (592, 'Question Level Edit', 'question_level_edit', 'yes');
INSERT INTO `permissions` VALUES (593, 'Question Level Delete', 'question_level_delete', 'yes');
INSERT INTO `permissions` VALUES (594, 'Question Bank', 'question_bank', 'yes');
INSERT INTO `permissions` VALUES (595, 'Question Bank Add', 'question_bank_add', 'yes');
INSERT INTO `permissions` VALUES (596, 'Question Bank Edit', 'question_bank_edit', 'yes');
INSERT INTO `permissions` VALUES (597, 'Question Bank Delete', 'question_bank_delete', 'yes');
INSERT INTO `permissions` VALUES (598, 'Question Bank View', 'question_bank_view', 'yes');
INSERT INTO `permissions` VALUES (599, 'Online Exam', 'online_exam', 'yes');
INSERT INTO `permissions` VALUES (600, 'Online Exam Add', 'online_exam_add', 'yes');
INSERT INTO `permissions` VALUES (601, 'Online Exam Edit', 'online_exam_edit', 'yes');
INSERT INTO `permissions` VALUES (602, 'Online Exam Delete', 'online_exam_delete', 'yes');
INSERT INTO `permissions` VALUES (603, 'Instruction', 'instruction', 'yes');
INSERT INTO `permissions` VALUES (604, 'Instruction Add', 'instruction_add', 'yes');
INSERT INTO `permissions` VALUES (605, 'Instruction Edit', 'instruction_edit', 'yes');
INSERT INTO `permissions` VALUES (606, 'Instruction Delete', 'instruction_delete', 'yes');
INSERT INTO `permissions` VALUES (607, 'Instruction View', 'instruction_view', 'yes');
INSERT INTO `permissions` VALUES (608, 'Salary Template', 'salary_template', 'yes');
INSERT INTO `permissions` VALUES (609, 'Salary Template Add', 'salary_template_add', 'yes');
INSERT INTO `permissions` VALUES (610, 'Salary Template Edit', 'salary_template_edit', 'yes');
INSERT INTO `permissions` VALUES (611, 'Salary Template Delete', 'salary_template_delete', 'yes');
INSERT INTO `permissions` VALUES (612, 'Salary Template View', 'salary_template_view', 'yes');
INSERT INTO `permissions` VALUES (613, 'Hourly Template', 'hourly_template', 'yes');
INSERT INTO `permissions` VALUES (614, 'Hourly Template Add', 'hourly_template_add', 'yes');
INSERT INTO `permissions` VALUES (615, 'Hourly Template Edit', 'hourly_template_edit', 'yes');
INSERT INTO `permissions` VALUES (616, 'Hourly Template Delete', 'hourly_template_delete', 'yes');
INSERT INTO `permissions` VALUES (617, 'Manage Salary', 'manage_salary', 'yes');
INSERT INTO `permissions` VALUES (618, 'Manage Salary Add', 'manage_salary_add', 'yes');
INSERT INTO `permissions` VALUES (619, 'Manage Salary Edit', 'manage_salary_edit', 'yes');
INSERT INTO `permissions` VALUES (620, 'Manage Salary Delete', 'manage_salary_delete', 'yes');
INSERT INTO `permissions` VALUES (621, 'Manage Salary View', 'manage_salary_view', 'yes');
INSERT INTO `permissions` VALUES (622, 'Make Payment', 'make_payment', 'yes');
INSERT INTO `permissions` VALUES (623, 'Vendor', 'vendor', 'yes');
INSERT INTO `permissions` VALUES (624, 'Vendor Add', 'vendor_add', 'yes');
INSERT INTO `permissions` VALUES (625, 'Vendor Edit', 'vendor_edit', 'yes');
INSERT INTO `permissions` VALUES (626, 'Vendor Delete', 'vendor_delete', 'yes');
INSERT INTO `permissions` VALUES (627, 'Location', 'location', 'yes');
INSERT INTO `permissions` VALUES (628, 'Location Add', 'location_add', 'yes');
INSERT INTO `permissions` VALUES (629, 'Location Edit', 'location_edit', 'yes');
INSERT INTO `permissions` VALUES (630, 'Location Delete', 'location_delete', 'yes');
INSERT INTO `permissions` VALUES (631, 'Asset Category', 'asset_category', 'yes');
INSERT INTO `permissions` VALUES (632, 'Asset Category Add', 'asset_category_add', 'yes');
INSERT INTO `permissions` VALUES (633, 'Asset Category Edit', 'asset_category_edit', 'yes');
INSERT INTO `permissions` VALUES (634, 'Asset Category Delete', 'asset_category_delete', 'yes');
INSERT INTO `permissions` VALUES (635, 'Asset', 'asset', 'yes');
INSERT INTO `permissions` VALUES (636, 'Asset Add', 'asset_add', 'yes');
INSERT INTO `permissions` VALUES (637, 'Asset Edit', 'asset_edit', 'yes');
INSERT INTO `permissions` VALUES (638, 'Asset Delete', 'asset_delete', 'yes');
INSERT INTO `permissions` VALUES (639, 'Asset View', 'asset_view', 'yes');
INSERT INTO `permissions` VALUES (640, 'Asset Assignment', 'asset_assignment', 'yes');
INSERT INTO `permissions` VALUES (641, 'Asset Assignment Add', 'asset_assignment_add', 'yes');
INSERT INTO `permissions` VALUES (642, 'Asset Assignment Edit', 'asset_assignment_edit', 'yes');
INSERT INTO `permissions` VALUES (643, 'Asset Assignment Delete', 'asset_assignment_delete', 'yes');
INSERT INTO `permissions` VALUES (644, 'Asset Assignment View', 'asset_assignment_view', 'yes');
INSERT INTO `permissions` VALUES (645, 'Purchase', 'purchase', 'yes');
INSERT INTO `permissions` VALUES (646, 'Purchase Add', 'purchase_add', 'yes');
INSERT INTO `permissions` VALUES (647, 'Purchase Edit', 'purchase_edit', 'yes');
INSERT INTO `permissions` VALUES (648, 'Purchase Delete', 'purchase_delete', 'yes');
INSERT INTO `permissions` VALUES (649, 'Activities Category', 'activitiescategory', 'yes');
INSERT INTO `permissions` VALUES (650, 'Activities Category Add', 'activitiescategory_add', 'yes');
INSERT INTO `permissions` VALUES (651, 'Activities Category Edit', 'activitiescategory_edit', 'yes');
INSERT INTO `permissions` VALUES (652, 'Activities Category Delete', 'activitiescategory_delete', 'yes');
INSERT INTO `permissions` VALUES (653, 'Activities', 'activities', 'yes');
INSERT INTO `permissions` VALUES (654, 'Activities Add', 'activities_add', 'yes');
INSERT INTO `permissions` VALUES (655, 'Activities Delete', 'activities_delete', 'yes');
INSERT INTO `permissions` VALUES (656, 'Child Care', 'childcare', 'yes');
INSERT INTO `permissions` VALUES (657, 'Child Care Add', 'childcare_add', 'yes');
INSERT INTO `permissions` VALUES (658, 'Child Care Edit', 'childcare_edit', 'yes');
INSERT INTO `permissions` VALUES (659, 'Child Care Delete', 'childcare_delete', 'yes');
INSERT INTO `permissions` VALUES (660, 'Library Member', 'lmember', 'yes');
INSERT INTO `permissions` VALUES (661, 'Library Member Add', 'lmember_add', 'yes');
INSERT INTO `permissions` VALUES (662, 'Library Member Edit', 'lmember_edit', 'yes');
INSERT INTO `permissions` VALUES (663, 'Library Member Delete', 'lmember_delete', 'yes');
INSERT INTO `permissions` VALUES (664, 'Library Member View', 'lmember_view', 'yes');
INSERT INTO `permissions` VALUES (665, 'Books', 'book', 'yes');
INSERT INTO `permissions` VALUES (666, 'Books Add', 'book_add', 'yes');
INSERT INTO `permissions` VALUES (667, 'Books Edit', 'book_edit', 'yes');
INSERT INTO `permissions` VALUES (668, 'Books Delete', 'book_delete', 'yes');
INSERT INTO `permissions` VALUES (669, 'Issue Book', 'issue', 'yes');
INSERT INTO `permissions` VALUES (670, 'Issue Book Add', 'issue_add', 'yes');
INSERT INTO `permissions` VALUES (671, 'Issue Book Edit', 'issue_edit', 'yes');
INSERT INTO `permissions` VALUES (672, 'Issue Book View', 'issue_view', 'yes');
INSERT INTO `permissions` VALUES (673, 'Transport', 'transport', 'yes');
INSERT INTO `permissions` VALUES (674, 'Transport Add', 'transport_add', 'yes');
INSERT INTO `permissions` VALUES (675, 'Transport Edit', 'transport_edit', 'yes');
INSERT INTO `permissions` VALUES (676, 'Transport Delete', 'transport_delete', 'yes');
INSERT INTO `permissions` VALUES (677, 'Transport Member', 'tmember', 'yes');
INSERT INTO `permissions` VALUES (678, 'Transport Member Add', 'tmember_add', 'yes');
INSERT INTO `permissions` VALUES (679, 'Transport Member Edit', 'tmember_edit', 'yes');
INSERT INTO `permissions` VALUES (680, 'Transport Member Delete', 'tmember_delete', 'yes');
INSERT INTO `permissions` VALUES (681, 'Transport Member View', 'tmember_view', 'yes');
INSERT INTO `permissions` VALUES (682, 'Hostel', 'hostel', 'yes');
INSERT INTO `permissions` VALUES (683, 'Hostel Add', 'hostel_add', 'yes');
INSERT INTO `permissions` VALUES (684, 'Hostel Edit', 'hostel_edit', 'yes');
INSERT INTO `permissions` VALUES (685, 'Hostel Delete', 'hostel_delete', 'yes');
INSERT INTO `permissions` VALUES (686, 'Hostel Category', 'category', 'yes');
INSERT INTO `permissions` VALUES (687, 'Hostel Category Add', 'category_add', 'yes');
INSERT INTO `permissions` VALUES (688, 'Hostel Category Edit', 'category_edit', 'yes');
INSERT INTO `permissions` VALUES (689, 'Hostel Category Delete', 'category_delete', 'yes');
INSERT INTO `permissions` VALUES (690, 'Hostel Member', 'hmember', 'yes');
INSERT INTO `permissions` VALUES (691, 'Hostel Member Add', 'hmember_add', 'yes');
INSERT INTO `permissions` VALUES (692, 'Hostel Member Edit', 'hmember_edit', 'yes');
INSERT INTO `permissions` VALUES (693, 'Hostel Member Delete', 'hmember_delete', 'yes');
INSERT INTO `permissions` VALUES (694, 'Hostel Member View', 'hmember_view', 'yes');
INSERT INTO `permissions` VALUES (695, 'Fee Types', 'feetypes', 'yes');
INSERT INTO `permissions` VALUES (696, 'Fee Types Add', 'feetypes_add', 'yes');
INSERT INTO `permissions` VALUES (697, 'Fee Types Edit', 'feetypes_edit', 'yes');
INSERT INTO `permissions` VALUES (698, 'Fee Types Delete', 'feetypes_delete', 'yes');
INSERT INTO `permissions` VALUES (699, 'Invoice', 'invoice', 'yes');
INSERT INTO `permissions` VALUES (700, 'Invoice Add', 'invoice_add', 'yes');
INSERT INTO `permissions` VALUES (701, 'Invoice Edit', 'invoice_edit', 'yes');
INSERT INTO `permissions` VALUES (702, 'Invoice Delete', 'invoice_delete', 'yes');
INSERT INTO `permissions` VALUES (703, 'Invoice View', 'invoice_view', 'yes');
INSERT INTO `permissions` VALUES (704, 'Payment History', 'paymenthistory', 'yes');
INSERT INTO `permissions` VALUES (705, 'Payment History Edit', 'paymenthistory_edit', 'yes');
INSERT INTO `permissions` VALUES (706, 'Payment History Delete', 'paymenthistory_delete', 'yes');
INSERT INTO `permissions` VALUES (707, 'Expense', 'expense', 'yes');
INSERT INTO `permissions` VALUES (708, 'Expense Add', 'expense_add', 'yes');
INSERT INTO `permissions` VALUES (709, 'Expense Edit', 'expense_edit', 'yes');
INSERT INTO `permissions` VALUES (710, 'Expense Delete', 'expense_delete', 'yes');
INSERT INTO `permissions` VALUES (711, 'Income', 'income', 'yes');
INSERT INTO `permissions` VALUES (712, 'Income Add', 'income_add', 'yes');
INSERT INTO `permissions` VALUES (713, 'Income Edit', 'income_edit', 'yes');
INSERT INTO `permissions` VALUES (714, 'Income Delete', 'income_delete', 'yes');
INSERT INTO `permissions` VALUES (715, 'Global Payment', 'global_payment', 'yes');
INSERT INTO `permissions` VALUES (716, 'Notice', 'notice', 'yes');
INSERT INTO `permissions` VALUES (717, 'Notice Add', 'notice_add', 'yes');
INSERT INTO `permissions` VALUES (718, 'Notice Edit', 'notice_edit', 'yes');
INSERT INTO `permissions` VALUES (719, 'Notice Delete', 'notice_delete', 'yes');
INSERT INTO `permissions` VALUES (720, 'Notice View', 'notice_view', 'yes');
INSERT INTO `permissions` VALUES (721, 'Event', 'event', 'yes');
INSERT INTO `permissions` VALUES (722, 'Event Add', 'event_add', 'yes');
INSERT INTO `permissions` VALUES (723, 'Event Edit', 'event_edit', 'yes');
INSERT INTO `permissions` VALUES (724, 'Event Delete', 'event_delete', 'yes');
INSERT INTO `permissions` VALUES (725, 'Event View', 'event_view', 'yes');
INSERT INTO `permissions` VALUES (726, 'Holiday', 'holiday', 'yes');
INSERT INTO `permissions` VALUES (727, 'Holiday Add', 'holiday_add', 'yes');
INSERT INTO `permissions` VALUES (728, 'Holiday Edit', 'holiday_edit', 'yes');
INSERT INTO `permissions` VALUES (729, 'Holiday Delete', 'holiday_delete', 'yes');
INSERT INTO `permissions` VALUES (730, 'Holiday View', 'holiday_view', 'yes');
INSERT INTO `permissions` VALUES (731, 'Classes Report', 'classesreport', 'yes');
INSERT INTO `permissions` VALUES (732, 'Student Report', 'studentreport', 'yes');
INSERT INTO `permissions` VALUES (733, 'ID Card Report', 'idcardreport', 'yes');
INSERT INTO `permissions` VALUES (734, 'Admit Card Report', 'admitcardreport', 'yes');
INSERT INTO `permissions` VALUES (735, 'Routine Report', 'routinereport', 'yes');
INSERT INTO `permissions` VALUES (736, 'Exam Schedule Report', 'examschedulereport', 'yes');
INSERT INTO `permissions` VALUES (737, 'Attendance Report', 'attendancereport', 'yes');
INSERT INTO `permissions` VALUES (738, 'Attendance Overview Report', 'attendanceoverviewreport', 'yes');
INSERT INTO `permissions` VALUES (739, 'Terminal Report', 'terminalreport', 'yes');
INSERT INTO `permissions` VALUES (740, 'Merit Stage Report', 'meritstagereport', 'yes');
INSERT INTO `permissions` VALUES (741, 'Tabulation Sheet Report', 'tabulationsheetreport', 'yes');
INSERT INTO `permissions` VALUES (742, 'Mark Sheet Report', 'marksheetreport', 'yes');
INSERT INTO `permissions` VALUES (743, 'Progress Card Report', 'progresscardreport', 'yes');
INSERT INTO `permissions` VALUES (744, 'Online Exam Report', 'onlineexamreport', 'yes');
INSERT INTO `permissions` VALUES (745, 'Certificate Report', 'certificatereport', 'yes');
INSERT INTO `permissions` VALUES (746, 'Fees Report', 'feesreport', 'yes');
INSERT INTO `permissions` VALUES (747, 'Due Fees Report', 'duefeesreport', 'yes');
INSERT INTO `permissions` VALUES (748, 'Balance Fees Report', 'balancefeesreport', 'yes');
INSERT INTO `permissions` VALUES (749, 'Transaction', 'transactionreport', 'yes');
INSERT INTO `permissions` VALUES (750, 'Student Fine Report', 'studentfinereport', 'yes');
INSERT INTO `permissions` VALUES (751, 'Visitor Information', 'visitorinfo', 'yes');
INSERT INTO `permissions` VALUES (752, 'Visitor Information Delete', 'visitorinfo_delete', 'yes');
INSERT INTO `permissions` VALUES (753, 'Visitor Infomation View', 'visitorinfo_view', 'yes');
INSERT INTO `permissions` VALUES (754, 'Academic Year', 'schoolyear', 'yes');
INSERT INTO `permissions` VALUES (755, 'Academic Year Add', 'schoolyear_add', 'yes');
INSERT INTO `permissions` VALUES (756, 'Academic Year Edit', 'schoolyear_edit', 'yes');
INSERT INTO `permissions` VALUES (757, 'Academic Year Delete', 'schoolyear_delete', 'yes');
INSERT INTO `permissions` VALUES (758, 'Student Group', 'studentgroup', 'yes');
INSERT INTO `permissions` VALUES (759, 'Student Group Add', 'studentgroup_add', 'yes');
INSERT INTO `permissions` VALUES (760, 'Student Group Edit', 'studentgroup_edit', 'yes');
INSERT INTO `permissions` VALUES (761, 'Student Group Delete', 'studentgroup_delete', 'yes');
INSERT INTO `permissions` VALUES (762, 'Complain', 'complain', 'yes');
INSERT INTO `permissions` VALUES (763, 'Complain Add', 'complain_add', 'yes');
INSERT INTO `permissions` VALUES (764, 'Complain Edit', 'complain_edit', 'yes');
INSERT INTO `permissions` VALUES (765, 'Complain Delete', 'complain_delete', 'yes');
INSERT INTO `permissions` VALUES (766, 'Complain View', 'complain_view', 'yes');
INSERT INTO `permissions` VALUES (767, 'Certificate Template', 'certificate_template', 'yes');
INSERT INTO `permissions` VALUES (768, 'Certificate Template Add', 'certificate_template_add', 'yes');
INSERT INTO `permissions` VALUES (769, 'Certificate Template Edit', 'certificate_template_edit', 'yes');
INSERT INTO `permissions` VALUES (770, 'Certificate Template Delete', 'certificate_template_delete', 'yes');
INSERT INTO `permissions` VALUES (771, 'Certificate Template View', 'certificate_template_view', 'yes');
INSERT INTO `permissions` VALUES (772, 'System Admin', 'systemadmin', 'yes');
INSERT INTO `permissions` VALUES (773, 'System Admin Add', 'systemadmin_add', 'yes');
INSERT INTO `permissions` VALUES (774, 'System Admin Edit', 'systemadmin_edit', 'yes');
INSERT INTO `permissions` VALUES (775, 'System Admin Delete', 'systemadmin_delete', 'yes');
INSERT INTO `permissions` VALUES (776, 'System Admin View', 'systemadmin_view', 'yes');
INSERT INTO `permissions` VALUES (777, 'Reset Password', 'resetpassword', 'yes');
INSERT INTO `permissions` VALUES (778, 'Social Link', 'sociallink', 'yes');
INSERT INTO `permissions` VALUES (779, 'Social Link Add', 'sociallink_add', 'yes');
INSERT INTO `permissions` VALUES (780, 'Social Link Edit', 'sociallink_edit', 'yes');
INSERT INTO `permissions` VALUES (781, 'Social Link Delete', 'sociallink_delete', 'yes');
INSERT INTO `permissions` VALUES (782, 'Mail / SMS Template', 'mailandsmstemplate', 'yes');
INSERT INTO `permissions` VALUES (783, 'Mail / SMS Template Add', 'mailandsmstemplate_add', 'yes');
INSERT INTO `permissions` VALUES (784, 'Mail / SMS Template Edit', 'mailandsmstemplate_edit', 'yes');
INSERT INTO `permissions` VALUES (785, 'Mail / SMS Template Delete', 'mailandsmstemplate_delete', 'yes');
INSERT INTO `permissions` VALUES (786, 'Mail / SMS Template View', 'mailandsmstemplate_view', 'yes');
INSERT INTO `permissions` VALUES (787, 'Import', 'bulkimport ', 'yes');
INSERT INTO `permissions` VALUES (788, 'Backup', 'backup', 'yes');
INSERT INTO `permissions` VALUES (789, 'Role', 'usertype', 'yes');
INSERT INTO `permissions` VALUES (790, 'Role Add', 'usertype_add', 'yes');
INSERT INTO `permissions` VALUES (791, 'Role Edit', 'usertype_edit', 'yes');
INSERT INTO `permissions` VALUES (792, 'Role Delete', 'usertype_delete', 'yes');
INSERT INTO `permissions` VALUES (793, 'Permission', 'permission', 'yes');
INSERT INTO `permissions` VALUES (794, 'Auto Update', 'update', 'yes');
INSERT INTO `permissions` VALUES (795, 'General Setting', 'setting', 'yes');
INSERT INTO `permissions` VALUES (796, 'General Setting Edit', 'setting_edit', 'yes');
INSERT INTO `permissions` VALUES (797, 'Payment Settings', 'paymentsettings', 'yes');
INSERT INTO `permissions` VALUES (798, 'SMS Settings', 'smssettings', 'yes');
INSERT INTO `permissions` VALUES (799, 'Pages', 'pages', 'yes');
INSERT INTO `permissions` VALUES (800, 'Pages Add', 'pages_add', 'yes');
INSERT INTO `permissions` VALUES (801, 'Pages Edit', 'pages_edit', 'yes');
INSERT INTO `permissions` VALUES (802, 'Pages Delete', 'pages_delete', 'yes');
INSERT INTO `permissions` VALUES (803, 'Frontend Setting', 'frontend_setting', 'yes');
INSERT INTO `permissions` VALUES (804, 'Promo', 'promo', 'yes');
INSERT INTO `permissions` VALUES (805, 'Promo View', 'promo_view', 'yes');


-- ----------------------------
-- Records of mobile_permission_relationships
-- ----------------------------
INSERT INTO `mobile_permission_relationships` VALUES (501, 3);
INSERT INTO `mobile_permission_relationships` VALUES (512, 3);
INSERT INTO `mobile_permission_relationships` VALUES (526, 3);
INSERT INTO `mobile_permission_relationships` VALUES (539, 3);
INSERT INTO `mobile_permission_relationships` VALUES (543, 3);
INSERT INTO `mobile_permission_relationships` VALUES (544, 3);
INSERT INTO `mobile_permission_relationships` VALUES (548, 3);
INSERT INTO `mobile_permission_relationships` VALUES (561, 3);
INSERT INTO `mobile_permission_relationships` VALUES (571, 3);
INSERT INTO `mobile_permission_relationships` VALUES (579, 3);
INSERT INTO `mobile_permission_relationships` VALUES (580, 3);
INSERT INTO `mobile_permission_relationships` VALUES (653, 3);
INSERT INTO `mobile_permission_relationships` VALUES (660, 3);
INSERT INTO `mobile_permission_relationships` VALUES (665, 3);
INSERT INTO `mobile_permission_relationships` VALUES (669, 3);
INSERT INTO `mobile_permission_relationships` VALUES (672, 3);
INSERT INTO `mobile_permission_relationships` VALUES (673, 3);
INSERT INTO `mobile_permission_relationships` VALUES (677, 3);
INSERT INTO `mobile_permission_relationships` VALUES (682, 3);
INSERT INTO `mobile_permission_relationships` VALUES (686, 3);
INSERT INTO `mobile_permission_relationships` VALUES (690, 3);
INSERT INTO `mobile_permission_relationships` VALUES (699, 3);
INSERT INTO `mobile_permission_relationships` VALUES (703, 3);
INSERT INTO `mobile_permission_relationships` VALUES (704, 3);
INSERT INTO `mobile_permission_relationships` VALUES (716, 3);
INSERT INTO `mobile_permission_relationships` VALUES (720, 3);
INSERT INTO `mobile_permission_relationships` VALUES (721, 3);
INSERT INTO `mobile_permission_relationships` VALUES (725, 3);
INSERT INTO `mobile_permission_relationships` VALUES (726, 3);
INSERT INTO `mobile_permission_relationships` VALUES (730, 3);
INSERT INTO `mobile_permission_relationships` VALUES (762, 3);
INSERT INTO `mobile_permission_relationships` VALUES (763, 3);
INSERT INTO `mobile_permission_relationships` VALUES (501, 4);
INSERT INTO `mobile_permission_relationships` VALUES (512, 4);
INSERT INTO `mobile_permission_relationships` VALUES (516, 4);
INSERT INTO `mobile_permission_relationships` VALUES (526, 4);
INSERT INTO `mobile_permission_relationships` VALUES (535, 4);
INSERT INTO `mobile_permission_relationships` VALUES (544, 4);
INSERT INTO `mobile_permission_relationships` VALUES (548, 4);
INSERT INTO `mobile_permission_relationships` VALUES (550, 4);
INSERT INTO `mobile_permission_relationships` VALUES (561, 4);
INSERT INTO `mobile_permission_relationships` VALUES (571, 4);
INSERT INTO `mobile_permission_relationships` VALUES (573, 4);
INSERT INTO `mobile_permission_relationships` VALUES (579, 4);
INSERT INTO `mobile_permission_relationships` VALUES (580, 4);
INSERT INTO `mobile_permission_relationships` VALUES (653, 4);
INSERT INTO `mobile_permission_relationships` VALUES (656, 4);
INSERT INTO `mobile_permission_relationships` VALUES (660, 4);
INSERT INTO `mobile_permission_relationships` VALUES (664, 4);
INSERT INTO `mobile_permission_relationships` VALUES (665, 4);
INSERT INTO `mobile_permission_relationships` VALUES (669, 4);
INSERT INTO `mobile_permission_relationships` VALUES (672, 4);
INSERT INTO `mobile_permission_relationships` VALUES (673, 4);
INSERT INTO `mobile_permission_relationships` VALUES (677, 4);
INSERT INTO `mobile_permission_relationships` VALUES (681, 4);
INSERT INTO `mobile_permission_relationships` VALUES (682, 4);
INSERT INTO `mobile_permission_relationships` VALUES (686, 4);
INSERT INTO `mobile_permission_relationships` VALUES (690, 4);
INSERT INTO `mobile_permission_relationships` VALUES (694, 4);
INSERT INTO `mobile_permission_relationships` VALUES (699, 4);
INSERT INTO `mobile_permission_relationships` VALUES (703, 4);
INSERT INTO `mobile_permission_relationships` VALUES (704, 4);
INSERT INTO `mobile_permission_relationships` VALUES (716, 4);
INSERT INTO `mobile_permission_relationships` VALUES (720, 4);
INSERT INTO `mobile_permission_relationships` VALUES (721, 4);
INSERT INTO `mobile_permission_relationships` VALUES (725, 4);
INSERT INTO `mobile_permission_relationships` VALUES (726, 4);
INSERT INTO `mobile_permission_relationships` VALUES (730, 4);
INSERT INTO `mobile_permission_relationships` VALUES (762, 4);
INSERT INTO `mobile_permission_relationships` VALUES (763, 4);
INSERT INTO `mobile_permission_relationships` VALUES (804, 3);
INSERT INTO `mobile_permission_relationships` VALUES (805, 3);
INSERT INTO `mobile_permission_relationships` VALUES (804, 4);
INSERT INTO `mobile_permission_relationships` VALUES (805, 4);


-- ----------------------------
-- Records of menu
-- ----------------------------
INSERT INTO `menu` VALUES (1, 'dashboard', 'dashboard', 'fa-laptop', '', 1, 0, 10000);
INSERT INTO `menu` VALUES (2, 'student', 'student', 'icon-student', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (3, 'parents', 'parents', 'fa-user', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (4, 'teacher', 'teacher', 'icon-teacher', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (5, 'user', 'user', 'fa-users', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (6, 'main_academic', '#', 'icon-academicmain', '', 1, 0, 1000);
INSERT INTO `menu` VALUES (7, 'main_attendance', '#', 'icon-attendance', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (8, 'main_exam', '#', 'icon-exam', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (9, 'main_mark', '#', 'icon-markmain', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (10, 'conversation', 'conversation', 'fa-envelope', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (11, 'media', 'media', 'fa-film', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (12, 'mailandsms', 'mailandsms', 'icon-mailandsms', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (13, 'main_library', '#', 'icon-library', '', 0, 0, 390);
INSERT INTO `menu` VALUES (14, 'main_transport', '#', 'icon-bus', '', 0, 0, 350);
INSERT INTO `menu` VALUES (15, 'main_hostel', '#', 'icon-hhostel', '', 0, 0, 320);
INSERT INTO `menu` VALUES (16, 'main_account', '#', 'icon-account', '', 1, 0, 280);
INSERT INTO `menu` VALUES (17, 'main_announcement', '#', 'icon-noticemain', '', 1, 0, 230);
INSERT INTO `menu` VALUES (18, 'main_report', '#', 'fa-clipboard', '', 1, 0, 190);
INSERT INTO `menu` VALUES (19, 'visitorinfo', 'visitorinfo', 'icon-visitorinfo', '', 0, 0, 150);
INSERT INTO `menu` VALUES (20, 'main_administrator', '#', 'icon-administrator', '', 1, 0, 140);
INSERT INTO `menu` VALUES (21, 'main_settings', '#', 'fa-gavel', '', 1, 0, 40);
INSERT INTO `menu` VALUES (22, 'classes', 'classes', 'fa-sitemap', NULL, 1, 6, 5000);
INSERT INTO `menu` VALUES (23, 'section', 'section', 'fa-star', NULL, 1, 6, 4000);
INSERT INTO `menu` VALUES (24, 'subject', 'subject', 'icon-subject', NULL, 1, 6, 4500);
INSERT INTO `menu` VALUES (25, 'routine', 'routine', 'icon-routine', NULL, 1, 6, 1000);
INSERT INTO `menu` VALUES (26, 'syllabus', 'syllabus', 'icon-syllabus', NULL, 1, 6, 3500);
INSERT INTO `menu` VALUES (27, 'assignment', 'assignment', 'icon-assignment', NULL, 1, 6, 3000);
INSERT INTO `menu` VALUES (28, 'sattendance', 'sattendance', 'icon-sattendance', NULL, 1, 7, 1000);
INSERT INTO `menu` VALUES (29, 'tattendance', 'tattendance', 'icon-tattendance', NULL, 1, 7, 1000);
INSERT INTO `menu` VALUES (30, 'exam', 'exam', 'fa-pencil', NULL, 1, 8, 1000);
INSERT INTO `menu` VALUES (31, 'examschedule', 'examschedule', 'fa-puzzle-piece', NULL, 1, 8, 1000);
INSERT INTO `menu` VALUES (32, 'grade', 'grade', 'fa-signal', NULL, 1, 8, 1000);
INSERT INTO `menu` VALUES (33, 'eattendance', 'eattendance', 'icon-eattendance', NULL, 1, 8, 1000);
INSERT INTO `menu` VALUES (34, 'mark', 'mark', 'fa-flask', NULL, 1, 9, 1000);
INSERT INTO `menu` VALUES (35, 'markpercentage', 'markpercentage', 'icon-markpercentage', NULL, 1, 9, 1000);
INSERT INTO `menu` VALUES (36, 'promotion', 'promotion', 'icon-promotion', NULL, 1, 9, 1000);
INSERT INTO `menu` VALUES (37, 'notice', 'notice', 'fa-calendar', '', 1, 17, 220);
INSERT INTO `menu` VALUES (38, 'event', 'event', 'fa-calendar-check-o', '', 1, 17, 210);
INSERT INTO `menu` VALUES (39, 'holiday', 'holiday', 'icon-holiday', '', 1, 17, 200);
INSERT INTO `menu` VALUES (40, 'classreport', 'classesreport', 'icon-classreport', '', 1, 18, 1000);
INSERT INTO `menu` VALUES (41, 'attendancereport', 'attendancereport', 'icon-attendancereport', '', 1, 18, 940);
INSERT INTO `menu` VALUES (42, 'studentreport', 'studentreport', 'icon-studentreport', '', 0, 18, 990);
INSERT INTO `menu` VALUES (43, 'schoolyear', 'schoolyear', 'fa fa-calendar-plus-o', '', 1, 20, 130);
INSERT INTO `menu` VALUES (44, 'mailandsmstemplate', 'mailandsmstemplate', 'icon-template', '', 0, 20, 100);
INSERT INTO `menu` VALUES (46, 'backup', 'backup', 'fa-download', '', 0, 20, 80);
INSERT INTO `menu` VALUES (47, 'systemadmin', 'systemadmin', 'icon-systemadmin', '', 1, 20, 120);
INSERT INTO `menu` VALUES (48, 'resetpassword', 'resetpassword', 'icon-reset_password', '', 1, 20, 110);
INSERT INTO `menu` VALUES (49, 'permission', 'permission', 'icon-permission', '', 1, 20, 60);
INSERT INTO `menu` VALUES (50, 'usertype', 'usertype', 'icon-role', '', 1, 20, 70);
INSERT INTO `menu` VALUES (51, 'setting', 'setting', 'fa-gears', '', 1, 21, 30);
INSERT INTO `menu` VALUES (52, 'paymentsettings', 'paymentsettings', 'icon-paymentsettings', '', 0, 21, 20);
INSERT INTO `menu` VALUES (53, 'smssettings', 'smssettings', 'fa-wrench', '', 0, 21, 10);
INSERT INTO `menu` VALUES (54, 'invoice', 'invoice', 'icon-invoice', '', 1, 16, 260);
INSERT INTO `menu` VALUES (55, 'paymenthistory', 'paymenthistory', 'icon-payment', '', 1, 16, 250);
INSERT INTO `menu` VALUES (56, 'transport', 'transport', 'icon-sbus', '', 0, 14, 340);
INSERT INTO `menu` VALUES (57, 'member', 'tmember', 'icon-member', '', 0, 14, 330);
INSERT INTO `menu` VALUES (58, 'hostel', 'hostel', 'icon-hostel', '', 0, 15, 310);
INSERT INTO `menu` VALUES (59, 'category', 'category', 'fa-leaf', '', 0, 15, 300);
INSERT INTO `menu` VALUES (61, 'member', 'hmember', 'icon-member', '', 0, 15, 290);
INSERT INTO `menu` VALUES (62, 'feetypes', 'feetypes', 'icon-feetypes', '', 1, 16, 270);
INSERT INTO `menu` VALUES (63, 'expense', 'expense', 'icon-expense', '', 1, 16, 240);
INSERT INTO `menu` VALUES (64, 'member', 'lmember', 'icon-member', '', 0, 13, 380);
INSERT INTO `menu` VALUES (65, 'books', 'book', 'icon-lbooks', '', 0, 13, 370);
INSERT INTO `menu` VALUES (66, 'issue', 'issue', 'icon-issue', '', 0, 13, 360);
INSERT INTO `menu` VALUES (69, 'import', 'bulkimport', 'fa-upload', '', 1, 20, 90);
INSERT INTO `menu` VALUES (70, 'update', 'update', 'fa-refresh', '', 0, 20, 50);
INSERT INTO `menu` VALUES (71, 'main_child', '#', 'fa-child', '', 0, 0, 430);
INSERT INTO `menu` VALUES (72, 'activitiescategory', 'activitiescategory', 'fa-pagelines', '', 0, 71, 420);
INSERT INTO `menu` VALUES (73, 'activities', 'activities', 'fa-fighter-jet', '', 0, 71, 410);
INSERT INTO `menu` VALUES (74, 'childcare', 'childcare', 'fa-wheelchair', '', 0, 71, 400);
INSERT INTO `menu` VALUES (75, 'uattendance', 'uattendance', 'fa-user-secret', NULL, 1, 7, 1000);
INSERT INTO `menu` VALUES (76, 'studentgroup', 'studentgroup', 'fa-object-group', '', 0, 20, 129);
INSERT INTO `menu` VALUES (77, 'vendor', 'vendor', 'fa-rss', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (78, 'location', 'location', 'fa-newspaper-o', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (79, 'asset_category', 'asset_category', 'fa-life-ring', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (80, 'asset', 'asset', 'fa-fax', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (81, 'complain', 'complain', 'fa-commenting', '', 0, 20, 128);
INSERT INTO `menu` VALUES (82, 'question_group', 'question_group', 'fa-question-circle', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (83, 'question_level', 'question_level', 'fa-level-up', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (84, 'question_bank', 'question_bank', 'fa-qrcode', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (85, 'online_exam', 'online_exam', 'fa-slideshare', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (86, 'instruction', 'instruction', 'fa-map-signs', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (87, 'take_exam', 'take_exam', 'fa-user-secret', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (88, 'online_exam', '#', 'fa-graduation-cap', '', 0, 0, 1000);
INSERT INTO `menu` VALUES (89, 'certificatereport', 'certificatereport', 'fa-diamond', '', 0, 18, 860);
INSERT INTO `menu` VALUES (90, 'certificate_template', 'certificate_template', 'fa-certificate', '', 0, 20, 128);
INSERT INTO `menu` VALUES (91, 'main_payroll', '#', 'fa-usd', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (92, 'salary_template', 'salary_template', 'fa-calculator', '', 1, 91, 1000);
INSERT INTO `menu` VALUES (93, 'hourly_template', 'hourly_template', 'fa fa-clock-o', '', 1, 91, 1000);
INSERT INTO `menu` VALUES (94, 'manage_salary', 'manage_salary', 'fa-beer', '', 1, 91, 1000);
INSERT INTO `menu` VALUES (95, 'make_payment', 'make_payment', 'fa-money', NULL, 1, 91, 1000);
INSERT INTO `menu` VALUES (96, 'main_asset_management', '#', 'fa-archive', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (97, 'asset_assignment', 'asset_assignment', 'fa-plug', NULL, 0, 96, 1000);
INSERT INTO `menu` VALUES (98, 'purchase', 'purchase', 'fa-cart-plus', NULL, 0, 96, 1000);
INSERT INTO `menu` VALUES (99, 'main_frontend', '#', 'fa-home', '', 0, 0, 30);
INSERT INTO `menu` VALUES (100, 'pages', 'pages', 'fa-connectdevelop', '', 0, 99, 1000);
INSERT INTO `menu` VALUES (101, 'frontend_setting', 'frontend_setting', 'fa-asterisk', '', 0, 99, 1000);
INSERT INTO `menu` VALUES (102, 'routinereport', 'routinereport', 'iniicon-routinereport', '', 1, 18, 960);
INSERT INTO `menu` VALUES (103, 'examschedulereport', 'examschedulereport', 'iniicon-examschedulereport', '', 1, 18, 950);
INSERT INTO `menu` VALUES (104, 'feesreport', 'feesreport', 'iniicon-feesreport', '', 1, 18, 850);
INSERT INTO `menu` VALUES (105, 'duefeesreport', 'duefeesreport', 'iniicon-duefeesreport', '', 1, 18, 840);
INSERT INTO `menu` VALUES (106, 'balancefeesreport', 'balancefeesreport', 'iniicon-balancefeesreport', '', 0, 18, 830);
INSERT INTO `menu` VALUES (107, 'transactionreport', 'transactionreport', 'iniicon-transactionreport', '', 1, 18, 820);
INSERT INTO `menu` VALUES (108, 'sociallink', 'sociallink', 'iniicon-sociallink', '', 0, 20, 109);
INSERT INTO `menu` VALUES (109, 'idcardreport', 'idcardreport', 'iniicon-idcardreport', '', 1, 18, 980);
INSERT INTO `menu` VALUES (110, 'admitcardreport', 'admitcardreport', 'iniicon-admitcardreport', '', 0, 18, 970);
INSERT INTO `menu` VALUES (111, 'studentfinereport', 'studentfinereport', 'iniicon-studentfinereport', '', 0, 18, 810);
INSERT INTO `menu` VALUES (112, 'attendanceoverviewreport', 'attendanceoverviewreport', 'iniicon-attendanceoverviewreport', '', 1, 18, 930);
INSERT INTO `menu` VALUES (113, 'income', 'income', 'iniicon-income', '', 1, 16, 239);
INSERT INTO `menu` VALUES (114, 'global_payment', 'global_payment', 'fa-balance-scale', '', 0, 16, 238);
INSERT INTO `menu` VALUES (115, 'terminalreport', 'terminalreport', 'iniicon-terminalreport', '', 1, 18, 920);
INSERT INTO `menu` VALUES (116, 'tabulationsheetreport', 'tabulationsheetreport', 'iniicon-tabulationsheetreport', '', 0, 18, 900);
INSERT INTO `menu` VALUES (117, 'marksheetreport', 'marksheetreport', 'iniicon-marksheetreport', '', 0, 18, 890);
INSERT INTO `menu` VALUES (118, 'meritstagereport', 'meritstagereport', 'iniicon-meritstagereport', '', 1, 18, 910);
INSERT INTO `menu` VALUES (119, 'progresscardreport', 'progresscardreport', 'iniicon-progresscardreport', '', 1, 18, 880);
INSERT INTO `menu` VALUES (120, 'onlineexamreport', 'onlineexamreport', 'iniicon-onlineexamreport', '', 0, 18, 870);
INSERT INTO `menu` VALUES (121, 'promo', 'promo', 'fa-calendar', '', 1, 0, 1000);


-- ----------------------------
-- Records of themes
-- ----------------------------
INSERT INTO `themes` VALUES (1, 1, 'Default', 1, 1, '#FFFFFF', '#2d353c');
INSERT INTO `themes` VALUES (2, 0, 'Blue', 0, 1, '#3c8dbc', '#2d353c');
INSERT INTO `themes` VALUES (3, 3, 'Black', 1, 1, '#fefefe', '#222222');
INSERT INTO `themes` VALUES (4, 4, 'Purple', 1, 1, '#605ca8', '#2d353c');
INSERT INTO `themes` VALUES (5, 5, 'Green', 1, 1, '#00a65a', '#2d353c');
INSERT INTO `themes` VALUES (6, 6, 'Red', 1, 1, '#dd4b39', '#2d353c');
INSERT INTO `themes` VALUES (7, 0, 'Yellow', 0, 1, '#f39c12', '#2d353c');
INSERT INTO `themes` VALUES (8, 7, 'Blue Light', 1, 1, '#3c8dbc', '#f9fafc');
INSERT INTO `themes` VALUES (9, 8, 'Black Light', 1, 1, '#fefefe', '#f9fafc');
INSERT INTO `themes` VALUES (10, 9, 'Purple Light', 1, 1, '#605ca8', '#f9fafc');
INSERT INTO `themes` VALUES (11, 10, 'Green Light', 1, 1, '#00a65a', '#f9fafc');
INSERT INTO `themes` VALUES (12, 11, 'Red Light', 1, 1, '#dd4b39', '#f9fafc');
INSERT INTO `themes` VALUES (13, 12, 'Yellow Light', 1, 1, '#f39c12', '#f9fafc');
INSERT INTO `themes` VALUES (14, 2, 'White Blue', 1, 1, '#ffffff', '#132035');

-- ----------------------------
-- Records of usertype
-- ----------------------------
INSERT INTO `usertype` VALUES (1, 'Admin', '2016-06-24 07:12:49', '2016-06-24 07:12:49', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (2, 'Teacher', '2016-06-24 07:13:13', '2016-06-24 07:13:13', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (3, 'Student', '2016-06-24 07:13:27', '2016-06-24 07:13:27', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (4, 'Parents', '2016-06-24 07:13:42', '2016-10-25 01:12:52', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (5, 'Accountant', '2016-06-24 07:13:54', '2016-06-24 07:13:54', 1, 'admin', 'Super Admin');

-- ----------------------------
-- Records of markpercentage
-- ----------------------------
INSERT INTO `markpercentage` VALUES (1, 'TOTAL', 100, NULL, NULL, NULL, '2018-10-08 03:25:39', '2018-10-08 03:25:39', 1, 'administrator', 'Admin');



