-- ----------------------------
-- Records of systemadmin
-- ----------------------------
INSERT INTO `systemadmin` VALUES (1, 'admin', '2018-07-27', 'Male', 'Unknown Admin', 'edu@jkt.co.id', '', '', '2018-07-27', 'default.png', 'administrator', '50644845050433f077a3c8c620fc0f78797d032e2e1e3c9b7ec9a5431fa1dce6aa8f565df9c44d4001f2d697918cabf40bbe8ea1e75d3d0183068fa1d953f5aa', 1, '2018-07-27 03:52:21', '2018-07-27 03:52:21', 0, 'administrator', 'Admin', 1, '', '', '1250000', '');

-- ----------------------------
-- Records of setting
-- ----------------------------
INSERT INTO `setting` VALUES ('address', '');
INSERT INTO `setting` VALUES ('attendance', '');
INSERT INTO `setting` VALUES ('attendance_notification', 'none');
INSERT INTO `setting` VALUES ('attendance_notification_template', '0');
INSERT INTO `setting` VALUES ('attendance_smsgateway', '0');
INSERT INTO `setting` VALUES ('automation', '5');
INSERT INTO `setting` VALUES ('auto_invoice_generate', '0');
INSERT INTO `setting` VALUES ('backend_theme', 'default');
INSERT INTO `setting` VALUES ('captcha_status', '1');
INSERT INTO `setting` VALUES ('currency_code', 'IDR');
INSERT INTO `setting` VALUES ('currency_symbol', 'Rp');
INSERT INTO `setting` VALUES ('email', '');
INSERT INTO `setting` VALUES ('footer', 'Powered by BRI');
INSERT INTO `setting` VALUES ('frontendorbackend', 'YES');
INSERT INTO `setting` VALUES ('frontend_theme', 'default');
INSERT INTO `setting` VALUES ('language', 'english');
INSERT INTO `setting` VALUES ('language_status', '0');
INSERT INTO `setting` VALUES ('note', '1');
INSERT INTO `setting` VALUES ('phone', '');
INSERT INTO `setting` VALUES ('photo', 'site.png');
INSERT INTO `setting` VALUES ('schoolID', @schoolID);
INSERT INTO `setting` VALUES ('school_type', 'classbase');
INSERT INTO `setting` VALUES ('school_year', '1');
INSERT INTO `setting` VALUES ('sname', @sname);
INSERT INTO `setting` VALUES ('student_ID_format', '1');
INSERT INTO `setting` VALUES ('updateversion', '4.0');
INSERT INTO `setting` VALUES ('weekends', '');
INSERT INTO `setting` VALUES ('mark_1', '1');


-- ----------------------------
-- Records of permission_relationships
-- ----------------------------
INSERT INTO `permission_relationships` VALUES (501, 4);
INSERT INTO `permission_relationships` VALUES (512, 4);
INSERT INTO `permission_relationships` VALUES (516, 4);
INSERT INTO `permission_relationships` VALUES (526, 4);
INSERT INTO `permission_relationships` VALUES (535, 4);
INSERT INTO `permission_relationships` VALUES (544, 4);
INSERT INTO `permission_relationships` VALUES (548, 4);
INSERT INTO `permission_relationships` VALUES (550, 4);
INSERT INTO `permission_relationships` VALUES (561, 4);
INSERT INTO `permission_relationships` VALUES (571, 4);
INSERT INTO `permission_relationships` VALUES (573, 4);
INSERT INTO `permission_relationships` VALUES (673, 4);
INSERT INTO `permission_relationships` VALUES (699, 4);
INSERT INTO `permission_relationships` VALUES (703, 4);
INSERT INTO `permission_relationships` VALUES (704, 4);
INSERT INTO `permission_relationships` VALUES (716, 4);
INSERT INTO `permission_relationships` VALUES (720, 4);
INSERT INTO `permission_relationships` VALUES (721, 4);
INSERT INTO `permission_relationships` VALUES (725, 4);
INSERT INTO `permission_relationships` VALUES (726, 4);
INSERT INTO `permission_relationships` VALUES (730, 4);
INSERT INTO `permission_relationships` VALUES (501, 5);
INSERT INTO `permission_relationships` VALUES (512, 5);
INSERT INTO `permission_relationships` VALUES (516, 5);
INSERT INTO `permission_relationships` VALUES (554, 5);
INSERT INTO `permission_relationships` VALUES (556, 5);
INSERT INTO `permission_relationships` VALUES (622, 5);
INSERT INTO `permission_relationships` VALUES (673, 5);
INSERT INTO `permission_relationships` VALUES (695, 5);
INSERT INTO `permission_relationships` VALUES (696, 5);
INSERT INTO `permission_relationships` VALUES (697, 5);
INSERT INTO `permission_relationships` VALUES (698, 5);
INSERT INTO `permission_relationships` VALUES (699, 5);
INSERT INTO `permission_relationships` VALUES (700, 5);
INSERT INTO `permission_relationships` VALUES (701, 5);
INSERT INTO `permission_relationships` VALUES (702, 5);
INSERT INTO `permission_relationships` VALUES (703, 5);
INSERT INTO `permission_relationships` VALUES (704, 5);
INSERT INTO `permission_relationships` VALUES (705, 5);
INSERT INTO `permission_relationships` VALUES (706, 5);
INSERT INTO `permission_relationships` VALUES (716, 5);
INSERT INTO `permission_relationships` VALUES (720, 5);
INSERT INTO `permission_relationships` VALUES (721, 5);
INSERT INTO `permission_relationships` VALUES (725, 5);
INSERT INTO `permission_relationships` VALUES (726, 5);
INSERT INTO `permission_relationships` VALUES (730, 5);
INSERT INTO `permission_relationships` VALUES (746, 5);
INSERT INTO `permission_relationships` VALUES (747, 5);
INSERT INTO `permission_relationships` VALUES (748, 5);
INSERT INTO `permission_relationships` VALUES (749, 5);
INSERT INTO `permission_relationships` VALUES (750, 5);
INSERT INTO `permission_relationships` VALUES (501, 2);
INSERT INTO `permission_relationships` VALUES (502, 2);
INSERT INTO `permission_relationships` VALUES (506, 2);
INSERT INTO `permission_relationships` VALUES (507, 2);
INSERT INTO `permission_relationships` VALUES (511, 2);
INSERT INTO `permission_relationships` VALUES (512, 2);
INSERT INTO `permission_relationships` VALUES (516, 2);
INSERT INTO `permission_relationships` VALUES (526, 2);
INSERT INTO `permission_relationships` VALUES (535, 2);
INSERT INTO `permission_relationships` VALUES (536, 2);
INSERT INTO `permission_relationships` VALUES (537, 2);
INSERT INTO `permission_relationships` VALUES (538, 2);
INSERT INTO `permission_relationships` VALUES (539, 2);
INSERT INTO `permission_relationships` VALUES (540, 2);
INSERT INTO `permission_relationships` VALUES (541, 2);
INSERT INTO `permission_relationships` VALUES (542, 2);
INSERT INTO `permission_relationships` VALUES (543, 2);
INSERT INTO `permission_relationships` VALUES (544, 2);
INSERT INTO `permission_relationships` VALUES (548, 2);
INSERT INTO `permission_relationships` VALUES (549, 2);
INSERT INTO `permission_relationships` VALUES (550, 2);
INSERT INTO `permission_relationships` VALUES (551, 2);
INSERT INTO `permission_relationships` VALUES (553, 2);
INSERT INTO `permission_relationships` VALUES (554, 2);
INSERT INTO `permission_relationships` VALUES (556, 2);
INSERT INTO `permission_relationships` VALUES (561, 2);
INSERT INTO `permission_relationships` VALUES (571, 2);
INSERT INTO `permission_relationships` VALUES (572, 2);
INSERT INTO `permission_relationships` VALUES (573, 2);
INSERT INTO `permission_relationships` VALUES (600, 2);
INSERT INTO `permission_relationships` VALUES (601, 2);
INSERT INTO `permission_relationships` VALUES (673, 2);
INSERT INTO `permission_relationships` VALUES (716, 2);
INSERT INTO `permission_relationships` VALUES (720, 2);
INSERT INTO `permission_relationships` VALUES (721, 2);
INSERT INTO `permission_relationships` VALUES (725, 2);
INSERT INTO `permission_relationships` VALUES (726, 2);
INSERT INTO `permission_relationships` VALUES (730, 2);
INSERT INTO `permission_relationships` VALUES (732, 2);
INSERT INTO `permission_relationships` VALUES (735, 2);
INSERT INTO `permission_relationships` VALUES (736, 2);
INSERT INTO `permission_relationships` VALUES (737, 2);
INSERT INTO `permission_relationships` VALUES (738, 2);
INSERT INTO `permission_relationships` VALUES (739, 2);
INSERT INTO `permission_relationships` VALUES (740, 2);
INSERT INTO `permission_relationships` VALUES (741, 2);
INSERT INTO `permission_relationships` VALUES (742, 2);
INSERT INTO `permission_relationships` VALUES (743, 2);
INSERT INTO `permission_relationships` VALUES (744, 2);
INSERT INTO `permission_relationships` VALUES (805, 2);
INSERT INTO `permission_relationships` VALUES (804, 2);
INSERT INTO `permission_relationships` VALUES (805, 4);
INSERT INTO `permission_relationships` VALUES (804, 4);
INSERT INTO `permission_relationships` VALUES (805, 5);
INSERT INTO `permission_relationships` VALUES (804, 5);
INSERT INTO `permission_relationships` VALUES (501, 1);
INSERT INTO `permission_relationships` VALUES (502, 1);
INSERT INTO `permission_relationships` VALUES (503, 1);
INSERT INTO `permission_relationships` VALUES (504, 1);
INSERT INTO `permission_relationships` VALUES (505, 1);
INSERT INTO `permission_relationships` VALUES (506, 1);
INSERT INTO `permission_relationships` VALUES (507, 1);
INSERT INTO `permission_relationships` VALUES (508, 1);
INSERT INTO `permission_relationships` VALUES (509, 1);
INSERT INTO `permission_relationships` VALUES (510, 1);
INSERT INTO `permission_relationships` VALUES (511, 1);
INSERT INTO `permission_relationships` VALUES (512, 1);
INSERT INTO `permission_relationships` VALUES (513, 1);
INSERT INTO `permission_relationships` VALUES (514, 1);
INSERT INTO `permission_relationships` VALUES (515, 1);
INSERT INTO `permission_relationships` VALUES (516, 1);
INSERT INTO `permission_relationships` VALUES (517, 1);
INSERT INTO `permission_relationships` VALUES (518, 1);
INSERT INTO `permission_relationships` VALUES (519, 1);
INSERT INTO `permission_relationships` VALUES (520, 1);
INSERT INTO `permission_relationships` VALUES (521, 1);
INSERT INTO `permission_relationships` VALUES (522, 1);
INSERT INTO `permission_relationships` VALUES (523, 1);
INSERT INTO `permission_relationships` VALUES (524, 1);
INSERT INTO `permission_relationships` VALUES (525, 1);
INSERT INTO `permission_relationships` VALUES (526, 1);
INSERT INTO `permission_relationships` VALUES (527, 1);
INSERT INTO `permission_relationships` VALUES (528, 1);
INSERT INTO `permission_relationships` VALUES (529, 1);
INSERT INTO `permission_relationships` VALUES (530, 1);
INSERT INTO `permission_relationships` VALUES (531, 1);
INSERT INTO `permission_relationships` VALUES (532, 1);
INSERT INTO `permission_relationships` VALUES (534, 1);
INSERT INTO `permission_relationships` VALUES (535, 1);
INSERT INTO `permission_relationships` VALUES (536, 1);
INSERT INTO `permission_relationships` VALUES (537, 1);
INSERT INTO `permission_relationships` VALUES (538, 1);
INSERT INTO `permission_relationships` VALUES (539, 1);
INSERT INTO `permission_relationships` VALUES (540, 1);
INSERT INTO `permission_relationships` VALUES (541, 1);
INSERT INTO `permission_relationships` VALUES (542, 1);
INSERT INTO `permission_relationships` VALUES (543, 1);
INSERT INTO `permission_relationships` VALUES (544, 1);
INSERT INTO `permission_relationships` VALUES (545, 1);
INSERT INTO `permission_relationships` VALUES (546, 1);
INSERT INTO `permission_relationships` VALUES (547, 1);
INSERT INTO `permission_relationships` VALUES (548, 1);
INSERT INTO `permission_relationships` VALUES (549, 1);
INSERT INTO `permission_relationships` VALUES (550, 1);
INSERT INTO `permission_relationships` VALUES (551, 1);
INSERT INTO `permission_relationships` VALUES (552, 1);
INSERT INTO `permission_relationships` VALUES (553, 1);
INSERT INTO `permission_relationships` VALUES (554, 1);
INSERT INTO `permission_relationships` VALUES (555, 1);
INSERT INTO `permission_relationships` VALUES (556, 1);
INSERT INTO `permission_relationships` VALUES (557, 1);
INSERT INTO `permission_relationships` VALUES (558, 1);
INSERT INTO `permission_relationships` VALUES (559, 1);
INSERT INTO `permission_relationships` VALUES (560, 1);
INSERT INTO `permission_relationships` VALUES (561, 1);
INSERT INTO `permission_relationships` VALUES (562, 1);
INSERT INTO `permission_relationships` VALUES (563, 1);
INSERT INTO `permission_relationships` VALUES (564, 1);
INSERT INTO `permission_relationships` VALUES (571, 1);
INSERT INTO `permission_relationships` VALUES (572, 1);
INSERT INTO `permission_relationships` VALUES (573, 1);
INSERT INTO `permission_relationships` VALUES (578, 1);
INSERT INTO `permission_relationships` VALUES (600, 1);
INSERT INTO `permission_relationships` VALUES (601, 1);
INSERT INTO `permission_relationships` VALUES (602, 1);
INSERT INTO `permission_relationships` VALUES (622, 1);
INSERT INTO `permission_relationships` VALUES (806, 1);
INSERT INTO `permission_relationships` VALUES (673, 1);
INSERT INTO `permission_relationships` VALUES (695, 1);
INSERT INTO `permission_relationships` VALUES (696, 1);
INSERT INTO `permission_relationships` VALUES (697, 1);
INSERT INTO `permission_relationships` VALUES (698, 1);
INSERT INTO `permission_relationships` VALUES (699, 1);
INSERT INTO `permission_relationships` VALUES (700, 1);
INSERT INTO `permission_relationships` VALUES (701, 1);
INSERT INTO `permission_relationships` VALUES (702, 1);
INSERT INTO `permission_relationships` VALUES (703, 1);
INSERT INTO `permission_relationships` VALUES (704, 1);
INSERT INTO `permission_relationships` VALUES (705, 1);
INSERT INTO `permission_relationships` VALUES (706, 1);
INSERT INTO `permission_relationships` VALUES (716, 1);
INSERT INTO `permission_relationships` VALUES (717, 1);
INSERT INTO `permission_relationships` VALUES (718, 1);
INSERT INTO `permission_relationships` VALUES (719, 1);
INSERT INTO `permission_relationships` VALUES (720, 1);
INSERT INTO `permission_relationships` VALUES (721, 1);
INSERT INTO `permission_relationships` VALUES (722, 1);
INSERT INTO `permission_relationships` VALUES (723, 1);
INSERT INTO `permission_relationships` VALUES (724, 1);
INSERT INTO `permission_relationships` VALUES (725, 1);
INSERT INTO `permission_relationships` VALUES (726, 1);
INSERT INTO `permission_relationships` VALUES (727, 1);
INSERT INTO `permission_relationships` VALUES (728, 1);
INSERT INTO `permission_relationships` VALUES (729, 1);
INSERT INTO `permission_relationships` VALUES (730, 1);
INSERT INTO `permission_relationships` VALUES (731, 1);
INSERT INTO `permission_relationships` VALUES (732, 1);
INSERT INTO `permission_relationships` VALUES (733, 1);
INSERT INTO `permission_relationships` VALUES (734, 1);
INSERT INTO `permission_relationships` VALUES (735, 1);
INSERT INTO `permission_relationships` VALUES (736, 1);
INSERT INTO `permission_relationships` VALUES (737, 1);
INSERT INTO `permission_relationships` VALUES (738, 1);
INSERT INTO `permission_relationships` VALUES (739, 1);
INSERT INTO `permission_relationships` VALUES (740, 1);
INSERT INTO `permission_relationships` VALUES (741, 1);
INSERT INTO `permission_relationships` VALUES (742, 1);
INSERT INTO `permission_relationships` VALUES (743, 1);
INSERT INTO `permission_relationships` VALUES (744, 1);
INSERT INTO `permission_relationships` VALUES (745, 1);
INSERT INTO `permission_relationships` VALUES (746, 1);
INSERT INTO `permission_relationships` VALUES (747, 1);
INSERT INTO `permission_relationships` VALUES (748, 1);
INSERT INTO `permission_relationships` VALUES (749, 1);
INSERT INTO `permission_relationships` VALUES (750, 1);
INSERT INTO `permission_relationships` VALUES (754, 1);
INSERT INTO `permission_relationships` VALUES (755, 1);
INSERT INTO `permission_relationships` VALUES (756, 1);
INSERT INTO `permission_relationships` VALUES (757, 1);
INSERT INTO `permission_relationships` VALUES (772, 1);
INSERT INTO `permission_relationships` VALUES (773, 1);
INSERT INTO `permission_relationships` VALUES (774, 1);
INSERT INTO `permission_relationships` VALUES (775, 1);
INSERT INTO `permission_relationships` VALUES (776, 1);
INSERT INTO `permission_relationships` VALUES (777, 1);
INSERT INTO `permission_relationships` VALUES (787, 1);
INSERT INTO `permission_relationships` VALUES (789, 1);
INSERT INTO `permission_relationships` VALUES (790, 1);
INSERT INTO `permission_relationships` VALUES (791, 1);
INSERT INTO `permission_relationships` VALUES (792, 1);
INSERT INTO `permission_relationships` VALUES (793, 1);
INSERT INTO `permission_relationships` VALUES (804, 1);
INSERT INTO `permission_relationships` VALUES (805, 1);
INSERT INTO `permission_relationships` VALUES (501, 3);
INSERT INTO `permission_relationships` VALUES (512, 3);
INSERT INTO `permission_relationships` VALUES (526, 3);
INSERT INTO `permission_relationships` VALUES (539, 3);
INSERT INTO `permission_relationships` VALUES (543, 3);
INSERT INTO `permission_relationships` VALUES (544, 3);
INSERT INTO `permission_relationships` VALUES (548, 3);
INSERT INTO `permission_relationships` VALUES (561, 3);
INSERT INTO `permission_relationships` VALUES (571, 3);
INSERT INTO `permission_relationships` VALUES (673, 3);
INSERT INTO `permission_relationships` VALUES (716, 3);
INSERT INTO `permission_relationships` VALUES (720, 3);
INSERT INTO `permission_relationships` VALUES (721, 3);
INSERT INTO `permission_relationships` VALUES (725, 3);
INSERT INTO `permission_relationships` VALUES (726, 3);
INSERT INTO `permission_relationships` VALUES (730, 3);
INSERT INTO `permission_relationships` VALUES (804, 3);
INSERT INTO `permission_relationships` VALUES (805, 3);


-- ----------------------------
-- Records of permissions
-- ----------------------------
INSERT INTO `permissions` VALUES (501, 'Dashboard', 'dashboard', 'yes');
INSERT INTO `permissions` VALUES (502, 'Student', 'student', 'yes');
INSERT INTO `permissions` VALUES (503, 'Student Add', 'student_add', 'yes');
INSERT INTO `permissions` VALUES (504, 'Student Edit', 'student_edit', 'yes');
INSERT INTO `permissions` VALUES (505, 'Student Delete', 'student_delete', 'yes');
INSERT INTO `permissions` VALUES (506, 'Student View', 'student_view', 'yes');
INSERT INTO `permissions` VALUES (507, 'Parents', 'parents', 'yes');
INSERT INTO `permissions` VALUES (508, 'Parents Add', 'parents_add', 'yes');
INSERT INTO `permissions` VALUES (509, 'Parents Edit', 'parents_edit', 'yes');
INSERT INTO `permissions` VALUES (510, 'Parents Delete', 'parents_delete', 'yes');
INSERT INTO `permissions` VALUES (511, 'Parents View', 'parents_view', 'yes');
INSERT INTO `permissions` VALUES (512, 'Teacher', 'teacher', 'yes');
INSERT INTO `permissions` VALUES (513, 'Teacher Add', 'teacher_add', 'yes');
INSERT INTO `permissions` VALUES (514, 'Teacher Edit', 'teacher_edit', 'yes');
INSERT INTO `permissions` VALUES (515, 'Teacher Delete', 'teacher_delete', 'yes');
INSERT INTO `permissions` VALUES (516, 'Teacher View', 'teacher_view', 'yes');
INSERT INTO `permissions` VALUES (517, 'User', 'user', 'yes');
INSERT INTO `permissions` VALUES (518, 'User Add', 'user_add', 'yes');
INSERT INTO `permissions` VALUES (519, 'User Edit', 'user_edit', 'yes');
INSERT INTO `permissions` VALUES (520, 'User Delete', 'user_delete', 'yes');
INSERT INTO `permissions` VALUES (521, 'User View', 'user_view', 'yes');
INSERT INTO `permissions` VALUES (522, 'Class', 'classes', 'yes');
INSERT INTO `permissions` VALUES (523, 'Class Add', 'classes_add', 'yes');
INSERT INTO `permissions` VALUES (524, 'Class Edit', 'classes_edit', 'yes');
INSERT INTO `permissions` VALUES (525, 'Class Delete', 'classes_delete', 'yes');
INSERT INTO `permissions` VALUES (526, 'Subject', 'subject', 'yes');
INSERT INTO `permissions` VALUES (527, 'Subject Add', 'subject_add', 'yes');
INSERT INTO `permissions` VALUES (528, 'Subject Edit', 'subject_edit', 'yes');
INSERT INTO `permissions` VALUES (529, 'Subject Delete', 'subject_delete', 'yes');
INSERT INTO `permissions` VALUES (530, 'Section', 'section', 'yes');
INSERT INTO `permissions` VALUES (531, 'Section Add', 'section_add', 'yes');
INSERT INTO `permissions` VALUES (532, 'Section Edit', 'section_edit', 'yes');
INSERT INTO `permissions` VALUES (533, 'Semester Delete', 'semester_delete', 'yes');
INSERT INTO `permissions` VALUES (534, 'Section Delete', 'section_delete', 'yes');
INSERT INTO `permissions` VALUES (535, 'Syllabus', 'syllabus', 'yes');
INSERT INTO `permissions` VALUES (536, 'Syllabus Add', 'syllabus_add', 'yes');
INSERT INTO `permissions` VALUES (537, 'Syllabus Edit', 'syllabus_edit', 'yes');
INSERT INTO `permissions` VALUES (538, 'Syllabus Delete', 'syllabus_delete', 'yes');
INSERT INTO `permissions` VALUES (539, 'Assignment', 'assignment', 'yes');
INSERT INTO `permissions` VALUES (540, 'Assignment Add', 'assignment_add', 'yes');
INSERT INTO `permissions` VALUES (541, 'Assignment Edit', 'assignment_edit', 'yes');
INSERT INTO `permissions` VALUES (542, 'Assignment Delete', 'assignment_delete', 'yes');
INSERT INTO `permissions` VALUES (543, 'Assignment View', 'assignment_view', 'yes');
INSERT INTO `permissions` VALUES (544, 'Routine', 'routine', 'yes');
INSERT INTO `permissions` VALUES (545, 'Routine Add', 'routine_add', 'yes');
INSERT INTO `permissions` VALUES (546, 'Routine Edit', 'routine_edit', 'yes');
INSERT INTO `permissions` VALUES (547, 'Routine Delete', 'routine_delete', 'yes');
INSERT INTO `permissions` VALUES (548, 'Student Attendance', 'sattendance', 'yes');
INSERT INTO `permissions` VALUES (549, 'Student Attendance Add', 'sattendance_add', 'yes');
INSERT INTO `permissions` VALUES (550, 'Student Attendance View', 'sattendance_view', 'yes');
INSERT INTO `permissions` VALUES (551, 'Teacher Attendance', 'tattendance', 'yes');
INSERT INTO `permissions` VALUES (552, 'Teacher Attendance Add', 'tattendance_add', 'yes');
INSERT INTO `permissions` VALUES (553, 'Teacher Attendance View', 'tattendance_view', 'yes');
INSERT INTO `permissions` VALUES (554, 'User Attendance', 'uattendance', 'yes');
INSERT INTO `permissions` VALUES (555, 'User Attendance Add', 'uattendance_add', 'yes');
INSERT INTO `permissions` VALUES (556, 'User Attendance View', 'uattendance_view', 'yes');
INSERT INTO `permissions` VALUES (557, 'Exam', 'exam', 'yes');
INSERT INTO `permissions` VALUES (558, 'Exam Add', 'exam_add', 'yes');
INSERT INTO `permissions` VALUES (559, 'Exam Edit', 'exam_edit', 'yes');
INSERT INTO `permissions` VALUES (560, 'Exam Delete', 'exam_delete', 'yes');
INSERT INTO `permissions` VALUES (561, 'Examschedule', 'examschedule', 'yes');
INSERT INTO `permissions` VALUES (562, 'Examschedule Add', 'examschedule_add', 'yes');
INSERT INTO `permissions` VALUES (563, 'Examschedule Edit', 'examschedule_edit', 'yes');
INSERT INTO `permissions` VALUES (564, 'Examschedule Delete', 'examschedule_delete', 'yes');
INSERT INTO `permissions` VALUES (571, 'Mark', 'mark', 'yes');
INSERT INTO `permissions` VALUES (572, 'Mark Add', 'mark_add', 'yes');
INSERT INTO `permissions` VALUES (573, 'Mark View', 'mark_view', 'yes');
INSERT INTO `permissions` VALUES (578, 'Promotion', 'promotion', 'yes');
INSERT INTO `permissions` VALUES (622, 'Make Payment', 'make_payment', 'yes');
INSERT INTO `permissions` VALUES (673, 'Application Guide', 'guidance', 'yes');
INSERT INTO `permissions` VALUES (695, 'Fee Types', 'feetypes', 'yes');
INSERT INTO `permissions` VALUES (696, 'Fee Types Add', 'feetypes_add', 'yes');
INSERT INTO `permissions` VALUES (697, 'Fee Types Edit', 'feetypes_edit', 'yes');
INSERT INTO `permissions` VALUES (698, 'Fee Types Delete', 'feetypes_delete', 'yes');
INSERT INTO `permissions` VALUES (699, 'Invoice', 'invoice', 'yes');
INSERT INTO `permissions` VALUES (700, 'Invoice Add', 'invoice_add', 'yes');
INSERT INTO `permissions` VALUES (701, 'Invoice Edit', 'invoice_edit', 'yes');
INSERT INTO `permissions` VALUES (702, 'Invoice Delete', 'invoice_delete', 'yes');
INSERT INTO `permissions` VALUES (703, 'Invoice View', 'invoice_view', 'yes');
INSERT INTO `permissions` VALUES (704, 'Payment History', 'paymenthistory', 'yes');
INSERT INTO `permissions` VALUES (705, 'Payment History Edit', 'paymenthistory_edit', 'yes');
INSERT INTO `permissions` VALUES (706, 'Payment History Delete', 'paymenthistory_delete', 'yes');
INSERT INTO `permissions` VALUES (716, 'Notice', 'notice', 'yes');
INSERT INTO `permissions` VALUES (717, 'Notice Add', 'notice_add', 'yes');
INSERT INTO `permissions` VALUES (718, 'Notice Edit', 'notice_edit', 'yes');
INSERT INTO `permissions` VALUES (719, 'Notice Delete', 'notice_delete', 'yes');
INSERT INTO `permissions` VALUES (720, 'Notice View', 'notice_view', 'yes');
INSERT INTO `permissions` VALUES (721, 'Event', 'event', 'yes');
INSERT INTO `permissions` VALUES (722, 'Event Add', 'event_add', 'yes');
INSERT INTO `permissions` VALUES (723, 'Event Edit', 'event_edit', 'yes');
INSERT INTO `permissions` VALUES (724, 'Event Delete', 'event_delete', 'yes');
INSERT INTO `permissions` VALUES (725, 'Event View', 'event_view', 'yes');
INSERT INTO `permissions` VALUES (726, 'Holiday', 'holiday', 'yes');
INSERT INTO `permissions` VALUES (727, 'Holiday Add', 'holiday_add', 'yes');
INSERT INTO `permissions` VALUES (728, 'Holiday Edit', 'holiday_edit', 'yes');
INSERT INTO `permissions` VALUES (729, 'Holiday Delete', 'holiday_delete', 'yes');
INSERT INTO `permissions` VALUES (730, 'Holiday View', 'holiday_view', 'yes');
INSERT INTO `permissions` VALUES (731, 'Classes Report', 'classesreport', 'yes');
INSERT INTO `permissions` VALUES (732, 'Student Report', 'studentreport', 'yes');
INSERT INTO `permissions` VALUES (733, 'ID Card Report', 'idcardreport', 'yes');
INSERT INTO `permissions` VALUES (734, 'Admit Card Report', 'admitcardreport', 'yes');
INSERT INTO `permissions` VALUES (735, 'Routine Report', 'routinereport', 'yes');
INSERT INTO `permissions` VALUES (736, 'Exam Schedule Report', 'examschedulereport', 'yes');
INSERT INTO `permissions` VALUES (737, 'Attendance Report', 'attendancereport', 'yes');
INSERT INTO `permissions` VALUES (738, 'Attendance Overview Report', 'attendanceoverviewreport', 'yes');
INSERT INTO `permissions` VALUES (739, 'Terminal Report', 'terminalreport', 'yes');
INSERT INTO `permissions` VALUES (740, 'Merit Stage Report', 'meritstagereport', 'yes');
INSERT INTO `permissions` VALUES (741, 'Tabulation Sheet Report', 'tabulationsheetreport', 'yes');
INSERT INTO `permissions` VALUES (742, 'Mark Sheet Report', 'marksheetreport', 'yes');
INSERT INTO `permissions` VALUES (743, 'Progress Card Report', 'progresscardreport', 'yes');
INSERT INTO `permissions` VALUES (745, 'Certificate Report', 'certificatereport', 'yes');
INSERT INTO `permissions` VALUES (746, 'Fees Report', 'feesreport', 'yes');
INSERT INTO `permissions` VALUES (747, 'Due Fees Report', 'duefeesreport', 'yes');
INSERT INTO `permissions` VALUES (748, 'Balance Fees Report', 'balancefeesreport', 'yes');
INSERT INTO `permissions` VALUES (749, 'Transaction', 'transactionreport', 'yes');
INSERT INTO `permissions` VALUES (750, 'Student Fine Report', 'studentfinereport', 'yes');
INSERT INTO `permissions` VALUES (754, 'Academic Year', 'schoolyear', 'yes');
INSERT INTO `permissions` VALUES (755, 'Academic Year Add', 'schoolyear_add', 'yes');
INSERT INTO `permissions` VALUES (756, 'Academic Year Edit', 'schoolyear_edit', 'yes');
INSERT INTO `permissions` VALUES (757, 'Academic Year Delete', 'schoolyear_delete', 'yes');
INSERT INTO `permissions` VALUES (772, 'System Admin', 'systemadmin', 'yes');
INSERT INTO `permissions` VALUES (773, 'System Admin Add', 'systemadmin_add', 'yes');
INSERT INTO `permissions` VALUES (774, 'System Admin Edit', 'systemadmin_edit', 'yes');
INSERT INTO `permissions` VALUES (775, 'System Admin Delete', 'systemadmin_delete', 'yes');
INSERT INTO `permissions` VALUES (776, 'System Admin View', 'systemadmin_view', 'yes');
INSERT INTO `permissions` VALUES (777, 'Reset Password', 'resetpassword', 'yes');
INSERT INTO `permissions` VALUES (787, 'Import', 'bulkimport ', 'yes');
INSERT INTO `permissions` VALUES (789, 'Role', 'usertype', 'yes');
INSERT INTO `permissions` VALUES (790, 'Role Add', 'usertype_add', 'yes');
INSERT INTO `permissions` VALUES (791, 'Role Edit', 'usertype_edit', 'yes');
INSERT INTO `permissions` VALUES (792, 'Role Delete', 'usertype_delete', 'yes');
INSERT INTO `permissions` VALUES (793, 'Permission', 'permission', 'yes');
INSERT INTO `permissions` VALUES (795, 'General Setting', 'setting', 'yes');
INSERT INTO `permissions` VALUES (796, 'General Setting Edit', 'setting_edit', 'yes');
INSERT INTO `permissions` VALUES (804, 'Promo', 'promo', 'yes');
INSERT INTO `permissions` VALUES (805, 'Promo View', 'promo_view', 'yes');
INSERT INTO `permissions` VALUES (806, 'Make Payment Edit', 'make_payment_edit', 'yes');


-- ----------------------------
-- Records of mobile_permission_relationships
-- ----------------------------
INSERT INTO `mobile_permission_relationships` VALUES (501, 3);
INSERT INTO `mobile_permission_relationships` VALUES (512, 3);
INSERT INTO `mobile_permission_relationships` VALUES (526, 3);
INSERT INTO `mobile_permission_relationships` VALUES (539, 3);
INSERT INTO `mobile_permission_relationships` VALUES (543, 3);
INSERT INTO `mobile_permission_relationships` VALUES (544, 3);
INSERT INTO `mobile_permission_relationships` VALUES (548, 3);
INSERT INTO `mobile_permission_relationships` VALUES (561, 3);
INSERT INTO `mobile_permission_relationships` VALUES (571, 3);
INSERT INTO `mobile_permission_relationships` VALUES (579, 3);
INSERT INTO `mobile_permission_relationships` VALUES (580, 3);
INSERT INTO `mobile_permission_relationships` VALUES (653, 3);
INSERT INTO `mobile_permission_relationships` VALUES (660, 3);
INSERT INTO `mobile_permission_relationships` VALUES (665, 3);
INSERT INTO `mobile_permission_relationships` VALUES (669, 3);
INSERT INTO `mobile_permission_relationships` VALUES (672, 3);
INSERT INTO `mobile_permission_relationships` VALUES (673, 3);
INSERT INTO `mobile_permission_relationships` VALUES (677, 3);
INSERT INTO `mobile_permission_relationships` VALUES (682, 3);
INSERT INTO `mobile_permission_relationships` VALUES (686, 3);
INSERT INTO `mobile_permission_relationships` VALUES (690, 3);
INSERT INTO `mobile_permission_relationships` VALUES (699, 3);
INSERT INTO `mobile_permission_relationships` VALUES (703, 3);
INSERT INTO `mobile_permission_relationships` VALUES (704, 3);
INSERT INTO `mobile_permission_relationships` VALUES (716, 3);
INSERT INTO `mobile_permission_relationships` VALUES (720, 3);
INSERT INTO `mobile_permission_relationships` VALUES (721, 3);
INSERT INTO `mobile_permission_relationships` VALUES (725, 3);
INSERT INTO `mobile_permission_relationships` VALUES (726, 3);
INSERT INTO `mobile_permission_relationships` VALUES (730, 3);
INSERT INTO `mobile_permission_relationships` VALUES (762, 3);
INSERT INTO `mobile_permission_relationships` VALUES (763, 3);
INSERT INTO `mobile_permission_relationships` VALUES (501, 4);
INSERT INTO `mobile_permission_relationships` VALUES (512, 4);
INSERT INTO `mobile_permission_relationships` VALUES (516, 4);
INSERT INTO `mobile_permission_relationships` VALUES (526, 4);
INSERT INTO `mobile_permission_relationships` VALUES (535, 4);
INSERT INTO `mobile_permission_relationships` VALUES (544, 4);
INSERT INTO `mobile_permission_relationships` VALUES (548, 4);
INSERT INTO `mobile_permission_relationships` VALUES (550, 4);
INSERT INTO `mobile_permission_relationships` VALUES (561, 4);
INSERT INTO `mobile_permission_relationships` VALUES (571, 4);
INSERT INTO `mobile_permission_relationships` VALUES (573, 4);
INSERT INTO `mobile_permission_relationships` VALUES (579, 4);
INSERT INTO `mobile_permission_relationships` VALUES (580, 4);
INSERT INTO `mobile_permission_relationships` VALUES (653, 4);
INSERT INTO `mobile_permission_relationships` VALUES (656, 4);
INSERT INTO `mobile_permission_relationships` VALUES (660, 4);
INSERT INTO `mobile_permission_relationships` VALUES (664, 4);
INSERT INTO `mobile_permission_relationships` VALUES (665, 4);
INSERT INTO `mobile_permission_relationships` VALUES (669, 4);
INSERT INTO `mobile_permission_relationships` VALUES (672, 4);
INSERT INTO `mobile_permission_relationships` VALUES (673, 4);
INSERT INTO `mobile_permission_relationships` VALUES (677, 4);
INSERT INTO `mobile_permission_relationships` VALUES (681, 4);
INSERT INTO `mobile_permission_relationships` VALUES (682, 4);
INSERT INTO `mobile_permission_relationships` VALUES (686, 4);
INSERT INTO `mobile_permission_relationships` VALUES (690, 4);
INSERT INTO `mobile_permission_relationships` VALUES (694, 4);
INSERT INTO `mobile_permission_relationships` VALUES (699, 4);
INSERT INTO `mobile_permission_relationships` VALUES (703, 4);
INSERT INTO `mobile_permission_relationships` VALUES (704, 4);
INSERT INTO `mobile_permission_relationships` VALUES (716, 4);
INSERT INTO `mobile_permission_relationships` VALUES (720, 4);
INSERT INTO `mobile_permission_relationships` VALUES (721, 4);
INSERT INTO `mobile_permission_relationships` VALUES (725, 4);
INSERT INTO `mobile_permission_relationships` VALUES (726, 4);
INSERT INTO `mobile_permission_relationships` VALUES (730, 4);
INSERT INTO `mobile_permission_relationships` VALUES (762, 4);
INSERT INTO `mobile_permission_relationships` VALUES (763, 4);
INSERT INTO `mobile_permission_relationships` VALUES (804, 3);
INSERT INTO `mobile_permission_relationships` VALUES (805, 3);
INSERT INTO `mobile_permission_relationships` VALUES (804, 4);
INSERT INTO `mobile_permission_relationships` VALUES (805, 4);



-- ----------------------------
-- Records of menu
-- ----------------------------
INSERT INTO `menu` VALUES (1, 'dashboard', 'dashboard', 'fa-laptop', '', 1, 0, 10000);
INSERT INTO `menu` VALUES (2, 'student', 'student', 'icon-student', NULL, 1, 0, 1200);
INSERT INTO `menu` VALUES (3, 'parents', 'parents', 'fa-user', NULL, 1, 0, 1300);
INSERT INTO `menu` VALUES (4, 'teacher', 'teacher', 'icon-teacher', NULL, 1, 0, 1400);
INSERT INTO `menu` VALUES (5, 'user', 'user', 'fa-users', NULL, 1, 0, 1100);
INSERT INTO `menu` VALUES (6, 'main_academic', '#', 'icon-academicmain', '', 1, 0, 1000);
INSERT INTO `menu` VALUES (7, 'main_attendance', '#', 'icon-attendance', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (8, 'main_exam', '#', 'icon-exam', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (9, 'main_mark', '#', 'icon-markmain', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (10, 'conversation', 'conversation', 'fa-envelope', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (11, 'media', 'media', 'fa-film', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (12, 'mailandsms', 'mailandsms', 'icon-mailandsms', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (13, 'main_library', '#', 'icon-library', '', 0, 0, 390);
INSERT INTO `menu` VALUES (14, 'main_transport', '#', 'icon-bus', '', 0, 0, 350);
INSERT INTO `menu` VALUES (15, 'main_hostel', '#', 'icon-hhostel', '', 0, 0, 320);
INSERT INTO `menu` VALUES (16, 'main_account', '#', 'icon-account', '', 1, 0, 280);
INSERT INTO `menu` VALUES (17, 'main_announcement', '#', 'icon-noticemain', '', 1, 0, 230);
INSERT INTO `menu` VALUES (18, 'main_report', '#', 'fa-clipboard', '', 1, 0, 190);
INSERT INTO `menu` VALUES (19, 'visitorinfo', 'visitorinfo', 'icon-visitorinfo', '', 0, 0, 150);
INSERT INTO `menu` VALUES (20, 'main_administrator', '#', 'icon-administrator', '', 1, 0, 140);
INSERT INTO `menu` VALUES (21, 'main_settings', '#', 'fa-gavel', '', 1, 0, 40);
INSERT INTO `menu` VALUES (22, 'classes', 'classes', 'fa-sitemap', NULL, 1, 6, 1010);
INSERT INTO `menu` VALUES (23, 'section', 'section', 'fa-star', NULL, 1, 6, 1009);
INSERT INTO `menu` VALUES (24, 'subject', 'subject', 'icon-subject', NULL, 1, 6, 1008);
INSERT INTO `menu` VALUES (25, 'routine', 'routine', 'icon-routine', NULL, 1, 6, 1005);
INSERT INTO `menu` VALUES (26, 'syllabus', 'syllabus', 'icon-syllabus', NULL, 1, 6, 1007);
INSERT INTO `menu` VALUES (27, 'assignment', 'assignment', 'icon-assignment', NULL, 1, 6, 1006);
INSERT INTO `menu` VALUES (28, 'sattendance', 'sattendance', 'icon-sattendance', NULL, 1, 7, 1000);
INSERT INTO `menu` VALUES (29, 'tattendance', 'tattendance', 'icon-tattendance', NULL, 1, 7, 1000);
INSERT INTO `menu` VALUES (30, 'exam', 'exam', 'fa-pencil', NULL, 1, 8, 1010);
INSERT INTO `menu` VALUES (31, 'examschedule', 'examschedule', 'fa-puzzle-piece', NULL, 1, 8, 1009);
INSERT INTO `menu` VALUES (32, 'grade', 'grade', 'fa-signal', NULL, 0, 8, 1000);
INSERT INTO `menu` VALUES (33, 'eattendance', 'eattendance', 'icon-eattendance', NULL, 0, 8, 1000);
INSERT INTO `menu` VALUES (34, 'mark', 'mark', 'fa-flask', NULL, 1, 8, 1008);
INSERT INTO `menu` VALUES (35, 'markpercentage', 'markpercentage', 'icon-markpercentage', NULL, 0, 9, 1000);
INSERT INTO `menu` VALUES (36, 'promotion', 'promotion', 'icon-promotion', NULL, 1, 9, 1000);
INSERT INTO `menu` VALUES (37, 'notice', 'notice', 'fa-calendar', '', 1, 17, 220);
INSERT INTO `menu` VALUES (38, 'event', 'event', 'fa-calendar-check-o', '', 1, 17, 210);
INSERT INTO `menu` VALUES (39, 'holiday', 'holiday', 'icon-holiday', '', 1, 17, 200);
INSERT INTO `menu` VALUES (40, 'classreport', 'classesreport', 'icon-classreport', '', 1, 18, 1000);
INSERT INTO `menu` VALUES (41, 'attendancereport', 'attendancereport', 'icon-attendancereport', '', 1, 18, 940);
INSERT INTO `menu` VALUES (42, 'studentreport', 'studentreport', 'icon-studentreport', '', 0, 18, 990);
INSERT INTO `menu` VALUES (43, 'schoolyear', 'schoolyear', 'fa fa-calendar-plus-o', '', 1, 20, 130);
INSERT INTO `menu` VALUES (44, 'mailandsmstemplate', 'mailandsmstemplate', 'icon-template', '', 0, 20, 100);
INSERT INTO `menu` VALUES (46, 'backup', 'backup', 'fa-download', '', 0, 20, 80);
INSERT INTO `menu` VALUES (47, 'systemadmin', 'systemadmin', 'icon-systemadmin', '', 1, 20, 120);
INSERT INTO `menu` VALUES (48, 'resetpassword', 'resetpassword', 'icon-reset_password', '', 1, 20, 110);
INSERT INTO `menu` VALUES (49, 'permission', 'permission', 'icon-permission', '', 1, 20, 60);
INSERT INTO `menu` VALUES (50, 'usertype', 'usertype', 'icon-role', '', 1, 20, 70);
INSERT INTO `menu` VALUES (51, 'setting', 'setting', 'fa-gears', '', 1, 21, 30);
INSERT INTO `menu` VALUES (52, 'paymentsettings', 'paymentsettings', 'icon-paymentsettings', '', 0, 21, 20);
INSERT INTO `menu` VALUES (53, 'smssettings', 'smssettings', 'fa-wrench', '', 0, 21, 10);
INSERT INTO `menu` VALUES (54, 'invoice', 'invoice', 'icon-invoice', '', 1, 16, 260);
INSERT INTO `menu` VALUES (55, 'paymenthistory', 'paymenthistory', 'icon-payment', '', 1, 16, 250);
INSERT INTO `menu` VALUES (56, 'guidance', 'guidance', 'icon-library', '', 1, 0, 10);
INSERT INTO `menu` VALUES (57, 'member', 'tmember', 'icon-member', '', 0, 14, 330);
INSERT INTO `menu` VALUES (58, 'hostel', 'hostel', 'icon-hostel', '', 0, 15, 310);
INSERT INTO `menu` VALUES (59, 'category', 'category', 'fa-leaf', '', 0, 15, 300);
INSERT INTO `menu` VALUES (61, 'member', 'hmember', 'icon-member', '', 0, 15, 290);
INSERT INTO `menu` VALUES (62, 'feetypes', 'feetypes', 'icon-feetypes', '', 1, 16, 270);
INSERT INTO `menu` VALUES (63, 'expense', 'expense', 'icon-expense', '', 0, 16, 240);
INSERT INTO `menu` VALUES (64, 'member', 'lmember', 'icon-member', '', 0, 13, 380);
INSERT INTO `menu` VALUES (65, 'books', 'book', 'icon-lbooks', '', 0, 13, 370);
INSERT INTO `menu` VALUES (66, 'issue', 'issue', 'icon-issue', '', 0, 13, 360);
INSERT INTO `menu` VALUES (69, 'import', 'bulkimport', 'fa-upload', '', 1, 20, 90);
INSERT INTO `menu` VALUES (70, 'update', 'update', 'fa-refresh', '', 0, 20, 50);
INSERT INTO `menu` VALUES (71, 'main_child', '#', 'fa-child', '', 0, 0, 430);
INSERT INTO `menu` VALUES (72, 'activitiescategory', 'activitiescategory', 'fa-pagelines', '', 0, 71, 420);
INSERT INTO `menu` VALUES (73, 'activities', 'activities', 'fa-fighter-jet', '', 0, 71, 410);
INSERT INTO `menu` VALUES (74, 'childcare', 'childcare', 'fa-wheelchair', '', 0, 71, 400);
INSERT INTO `menu` VALUES (75, 'uattendance', 'uattendance', 'fa-user-secret', NULL, 1, 7, 1000);
INSERT INTO `menu` VALUES (76, 'studentgroup', 'studentgroup', 'fa-object-group', '', 0, 20, 129);
INSERT INTO `menu` VALUES (77, 'vendor', 'vendor', 'fa-rss', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (78, 'location', 'location', 'fa-newspaper-o', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (79, 'asset_category', 'asset_category', 'fa-life-ring', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (80, 'asset', 'asset', 'fa-fax', '', 0, 96, 1000);
INSERT INTO `menu` VALUES (81, 'complain', 'complain', 'fa-commenting', '', 0, 20, 128);
INSERT INTO `menu` VALUES (82, 'question_group', 'question_group', 'fa-question-circle', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (83, 'question_level', 'question_level', 'fa-level-up', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (84, 'question_bank', 'question_bank', 'fa-qrcode', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (85, 'online_exam', 'online_exam', 'fa-slideshare', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (86, 'instruction', 'instruction', 'fa-map-signs', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (87, 'take_exam', 'take_exam', 'fa-user-secret', '', 0, 88, 1000);
INSERT INTO `menu` VALUES (88, 'online_exam', '#', 'fa-graduation-cap', '', 0, 0, 1000);
INSERT INTO `menu` VALUES (89, 'certificatereport', 'certificatereport', 'fa-diamond', '', 0, 18, 860);
INSERT INTO `menu` VALUES (90, 'certificate_template', 'certificate_template', 'fa-certificate', '', 0, 20, 128);
INSERT INTO `menu` VALUES (91, 'main_payroll', '#', 'fa-usd', NULL, 1, 0, 1000);
INSERT INTO `menu` VALUES (92, 'salary_template', 'salary_template', 'fa-calculator', '', 0, 91, 1000);
INSERT INTO `menu` VALUES (93, 'hourly_template', 'hourly_template', 'fa fa-clock-o', '', 0, 91, 1000);
INSERT INTO `menu` VALUES (94, 'manage_salary', 'manage_salary', 'fa-beer', '', 0, 91, 1000);
INSERT INTO `menu` VALUES (95, 'make_payment', 'make_payment', 'fa-money', NULL, 1, 91, 1000);
INSERT INTO `menu` VALUES (96, 'main_asset_management', '#', 'fa-archive', NULL, 0, 0, 1000);
INSERT INTO `menu` VALUES (97, 'asset_assignment', 'asset_assignment', 'fa-plug', NULL, 0, 96, 1000);
INSERT INTO `menu` VALUES (98, 'purchase', 'purchase', 'fa-cart-plus', NULL, 0, 96, 1000);
INSERT INTO `menu` VALUES (99, 'main_frontend', '#', 'fa-home', '', 0, 0, 30);
INSERT INTO `menu` VALUES (100, 'pages', 'pages', 'fa-connectdevelop', '', 0, 99, 1000);
INSERT INTO `menu` VALUES (101, 'frontend_setting', 'frontend_setting', 'fa-asterisk', '', 0, 99, 1000);
INSERT INTO `menu` VALUES (102, 'routinereport', 'routinereport', 'iniicon-routinereport', '', 1, 18, 960);
INSERT INTO `menu` VALUES (103, 'examschedulereport', 'examschedulereport', 'iniicon-examschedulereport', '', 1, 18, 950);
INSERT INTO `menu` VALUES (104, 'feesreport', 'feesreport', 'iniicon-feesreport', '', 0, 18, 850);
INSERT INTO `menu` VALUES (105, 'duefeesreport', 'duefeesreport', 'iniicon-duefeesreport', '', 1, 18, 840);
INSERT INTO `menu` VALUES (106, 'balancefeesreport', 'balancefeesreport', 'iniicon-balancefeesreport', '', 0, 18, 830);
INSERT INTO `menu` VALUES (107, 'transactionreport', 'transactionreport', 'iniicon-transactionreport', '', 1, 18, 820);
INSERT INTO `menu` VALUES (108, 'sociallink', 'sociallink', 'iniicon-sociallink', '', 0, 20, 109);
INSERT INTO `menu` VALUES (109, 'idcardreport', 'idcardreport', 'iniicon-idcardreport', '', 1, 18, 980);
INSERT INTO `menu` VALUES (110, 'admitcardreport', 'admitcardreport', 'iniicon-admitcardreport', '', 0, 18, 970);
INSERT INTO `menu` VALUES (111, 'studentfinereport', 'studentfinereport', 'iniicon-studentfinereport', '', 0, 18, 810);
INSERT INTO `menu` VALUES (112, 'attendanceoverviewreport', 'attendanceoverviewreport', 'iniicon-attendanceoverviewreport', '', 1, 18, 930);
INSERT INTO `menu` VALUES (113, 'income', 'income', 'iniicon-income', '', 0, 16, 239);
INSERT INTO `menu` VALUES (114, 'global_payment', 'global_payment', 'fa-balance-scale', '', 1, 16, 238);
INSERT INTO `menu` VALUES (115, 'terminalreport', 'terminalreport', 'iniicon-terminalreport', '', 1, 18, 920);
INSERT INTO `menu` VALUES (116, 'tabulationsheetreport', 'tabulationsheetreport', 'iniicon-tabulationsheetreport', '', 0, 18, 900);
INSERT INTO `menu` VALUES (117, 'marksheetreport', 'marksheetreport', 'iniicon-marksheetreport', '', 0, 18, 890);
INSERT INTO `menu` VALUES (118, 'meritstagereport', 'meritstagereport', 'iniicon-meritstagereport', '', 1, 18, 910);
INSERT INTO `menu` VALUES (119, 'progresscardreport', 'progresscardreport', 'iniicon-progresscardreport', '', 0, 18, 880);
INSERT INTO `menu` VALUES (120, 'onlineexamreport', 'onlineexamreport', 'iniicon-onlineexamreport', '', 0, 18, 870);
INSERT INTO `menu` VALUES (121, 'promo', 'promo', 'fa-calendar', '', 1, 0, 1000);


-- ----------------------------
-- Records of themes
-- ----------------------------
INSERT INTO `themes` VALUES (1, 1, 'Default', 1, 1, '#1D9AD6', '#1D9AD6');
INSERT INTO `themes` VALUES (2, 0, 'Blue', 0, 1, '#3c8dbc', '#2d353c');
INSERT INTO `themes` VALUES (3, 2, 'Black', 1, 1, '#231F20', '#231F20');
INSERT INTO `themes` VALUES (4, 3, 'Purple', 1, 1, '#684F90', '#684F90');
INSERT INTO `themes` VALUES (5, 4, 'Green', 1, 1, '#007A66', '#007A66');
INSERT INTO `themes` VALUES (6, 5, 'Red', 1, 1, '#F0493E', '#F0493E');
INSERT INTO `themes` VALUES (7, 6, 'Yellow', 1, 1, '#f39c12', '#f39c12');
INSERT INTO `themes` VALUES (8, 7, 'Blue Light', 1, 1, '#97DAF8', '#97DAF8');
INSERT INTO `themes` VALUES (9, 8, 'Black Light', 1, 1, '#999B9E', '#999B9E');
INSERT INTO `themes` VALUES (10, 9, 'Purple Light', 1, 1, '#A193BD', '#A193BD');
INSERT INTO `themes` VALUES (11, 10, 'Green Light', 1, 1, '#62ABA0', '#62ABA0');
INSERT INTO `themes` VALUES (12, 11, 'Red Light', 1, 1, '#F79F88', '#F79F88');
INSERT INTO `themes` VALUES (13, 12, 'Yellow Light', 1, 1, '#FFED96', '#FFED96');
INSERT INTO `themes` VALUES (14, 0, 'White Blue', 0, 1, '#ffffff', '#132035');


-- ----------------------------
-- Records of usertype
-- ----------------------------
INSERT INTO `usertype` VALUES (1, 'Admin', '2016-06-24 07:12:49', '2016-06-24 07:12:49', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (2, 'Teacher', '2016-06-24 07:13:13', '2016-06-24 07:13:13', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (3, 'Student', '2016-06-24 07:13:27', '2016-06-24 07:13:27', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (4, 'Parents', '2016-06-24 07:13:42', '2016-10-25 01:12:52', 1, 'admin', 'Super Admin');
INSERT INTO `usertype` VALUES (5, 'Accountant', '2016-06-24 07:13:54', '2016-06-24 07:13:54', 1, 'admin', 'Super Admin');

-- ----------------------------
-- Records of markpercentage
-- ----------------------------
INSERT INTO `markpercentage` VALUES (1, 'TOTAL', 100, NULL, NULL, NULL, '2018-10-08 03:25:39', '2018-10-08 03:25:39', 1, 'administrator', 'Admin');

-- ----------------------------
-- Records of feetypes
-- ----------------------------
INSERT INTO `feetypes` VALUES (1, 'Tagihan SPP', 'Don\'t delete it!');

